Repository vmware/alb-sdk, pull requests merged in 2021-05, with the labels that each got.

#1396 Auto updated assets for go models and clients
  .travis.yml
  go.mod
  go.sum
  go/examples/create_vs.go
  go/models/ip_reputation_type_match.go
  go/session/avisession.go
  go/session/avisession_test.go
  go/vendor/github.com/golang/glog/LICENSE
  go/vendor/github.com/golang/glog/README
  go/vendor/github.com/golang/glog/glog.go
  go/vendor/github.com/golang/glog/glog_file.go
  go/vendor/vendor.json
Labels: AUTO PR

#1404 Auto updated root sdk files
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: AUTO PR

#1403 Auto updated assets for docs
  docs/Alert/index.html
  docs/HTTPPolicySet/index.html
  docs/NetworkSecurityPolicy/index.html
  docs/SSLKeyAndCertificate/index.html
  docs/WafPolicy/index.html
Labels: AUTO PR

#1405 AV-106357 Added release workflow for sdk(python, java)
  .github/workflows/release.yml
Labels: Cherry-pick

#1408 Auto updated assets for go models and clients
  go/models/rm_add_vnic.go
Labels: AUTO PR

#1419 Auto updated assets for go models and clients
  go/models/g_c_p_one_arm_mode.go
  go/models/g_c_p_se_group_config.go
  go/models/g_c_p_two_arm_mode.go
Labels: AUTO PR

#1423 Update README.md
  go/README.md
Labels: cla-not-required

#1425 Revert "Dummy eng fork2"
  go/README.md
  python/avi/sdk/README.md
Labels: cla-not-required

#1426 Update README.md
  go/README.md
Labels: cla-not-required

#1422 Auto updated assets for go models and clients
  go/models/waf_application_signatures.go
  go/models/waf_policy.go
  go/models/waf_rule_group_overrides.go
  go/models/waf_rule_overrides.go
  go/models/web_application_signature_service_status.go
Labels: AUTO PR, cla-not-required

#1430 Auto updated assets for java
  java/src/com/vmware/avi/sdk/model/BgpPeer.java
  java/src/com/vmware/avi/sdk/model/GCPOneArmMode.java
  java/src/com/vmware/avi/sdk/model/GCPSeGroupConfig.java
  java/src/com/vmware/avi/sdk/model/GCPTwoArmMode.java
  java/src/com/vmware/avi/sdk/model/RmAddVnic.java
  java/src/com/vmware/avi/sdk/model/WafApplicationSignatures.java
  java/src/com/vmware/avi/sdk/model/WafPolicy.java
  java/src/com/vmware/avi/sdk/model/WafRuleGroupOverrides.java
  java/src/com/vmware/avi/sdk/model/WafRuleOverrides.java
  java/src/com/vmware/avi/sdk/model/WebApplicationSignatureServiceStatus.java
Labels: AUTO PR, cla-not-required

#1435 Auto updated assets for docs
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/Image/index.html
  docs/ServiceEngineGroup/index.html
  docs/WafApplicationSignatureProvider/index.html
  docs/WafPolicy/index.html
Labels: AUTO PR, cla-not-required

#1429 Auto updated assets for go models and clients
  go/clients/avi_client.go
  go/clients/inventoryfaultconfig_client.go
  go/clients/jwtprofile_client.go
  go/models/bgp_peer.go
  go/models/controller_faults.go
  go/models/inventory_fault_config.go
  go/models/inventory_fault_config_api_response.go
  go/models/j_w_s_key.go
  go/models/j_w_t_profile.go
  go/models/j_w_t_server_profile.go
  go/models/pool.go
  go/models/serviceengine_faults.go
  go/models/virtualservice_faults.go
Labels: AUTO PR, cla-not-required

#1433 Auto updated assets for python
  python/avi/migrationtools/f5_converter/test/test_migrationtool.py
  python/avi/migrationtools/vs_filter.py
  python/version.py
Labels: AUTO PR, cla-not-required
