Repository vmware/alb-sdk, pull requests merged in 2021-08, with the labels that each got.

#1511 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/ConnectionEventDetails.java
  java/src/com/vmware/avi/sdk/model/EventDetails.java
Labels: AUTO PR, cla-not-required

#1515 Auto updated assets for java eng
  java/pom.xml
Labels: AUTO PR, cla-not-required

#1512 Auto updated assets for python 21.1.1
  python/avi/migrationtools/ace_converter/ace_converter.py
  python/avi/migrationtools/ansible/ansible_config_converter.py
  python/avi/migrationtools/ansible/avi_config_to_ansible.py
  python/avi/migrationtools/avi_orphan_object.py
  python/avi/migrationtools/config_patch.py
  python/avi/migrationtools/f5_converter/clone_cross_tenant_obj.py
  python/avi/migrationtools/f5_converter/f5_converter.py
  python/avi/migrationtools/f5_discovery.py
  python/avi/migrationtools/gss_convertor/gss_convertor.py
  python/avi/migrationtools/netscaler_converter/netscaler_converter.py
  python/avi/migrationtools/netscaler_converter/test/netscaler_e2e_test.py
  python/avi/migrationtools/vs_filter.py
  python/avi/migrationtools/waf/avi_iwaf_vpatch.py
  python/avi/sdk/samples/alb_rules.py
  python/avi/sdk/samples/clone_vs.py
  python/avi/sdk/samples/clone_vs_segroup.py
  python/avi/sdk/samples/virtualservice_examples_api.py
  python/avi/sdk/samples/virtualservice_examples_saml_api.py
  python/avi/sdk/utils/app_logs/analyze_logs.py
  python/avi/sdk/utils/app_logs/fetch_logs.py
Labels: AUTO PR, cla-not-required

#1508 Auto updated assets for java 21.1.1
  java/src/com/vmware/avi/sdk/model/HttpCookiePersistenceProfile.java
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
Labels: AUTO PR, cla-not-required

#1518 Auto updated assets for python 20.1.7
  python/avi/migrationtools/ace_converter/ace_converter.py
  python/avi/migrationtools/ansible/ansible_config_converter.py
  python/avi/migrationtools/ansible/avi_config_to_ansible.py
  python/avi/migrationtools/avi_orphan_object.py
  python/avi/migrationtools/config_patch.py
  python/avi/migrationtools/f5_converter/clone_cross_tenant_obj.py
  python/avi/migrationtools/f5_converter/f5_converter.py
  python/avi/migrationtools/f5_discovery.py
  python/avi/migrationtools/gss_convertor/gss_convertor.py
  python/avi/migrationtools/netscaler_converter/netscaler_converter.py
  python/avi/migrationtools/netscaler_converter/test/netscaler_e2e_test.py
  python/avi/migrationtools/vs_filter.py
  python/avi/migrationtools/waf/avi_iwaf_vpatch.py
  python/avi/sdk/samples/alb_rules.py
  python/avi/sdk/samples/clone_vs.py
  python/avi/sdk/samples/clone_vs_segroup.py
  python/avi/sdk/samples/virtualservice_examples_api.py
  python/avi/sdk/samples/virtualservice_examples_saml_api.py
  python/avi/sdk/utils/app_logs/analyze_logs.py
  python/avi/sdk/utils/app_logs/fetch_logs.py
Labels: AUTO PR, cla-not-required

#1507 Auto updated assets for go models and clients 21.1.1
  go/models/http_cookie_persistence_profile.go
  go/models/inventory_fault_config.go
  go/models/service_engine_group.go
Labels: AUTO PR, cla-not-required

#1497 Auto updated assets for docs 21.1.1
  docs/ALBServicesConfig/index.html
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
  docs/ApplicationPersistenceProfile/index.html
  docs/CloudProperties/index.html
  docs/ControllerProperties/index.html
  docs/Image/index.html
  docs/InventoryFaultConfig/index.html
  docs/ServiceEngine/index.html
  docs/ServiceEngineGroup/index.html
  docs/VIMgrVcenterRuntime/index.html
Labels: AUTO PR, cla-not-required

#1489 Auto updated assets for docs 20.1.7
  docs/Alert/index.html
  docs/ServiceEngineGroup/index.html
Labels: AUTO PR, cla-not-required

#1514 Auto updated assets for python eng
  python/avi/migrationtools/ace_converter/ace_converter.py
  python/avi/migrationtools/ansible/ansible_config_converter.py
  python/avi/migrationtools/ansible/avi_config_to_ansible.py
  python/avi/migrationtools/avi_orphan_object.py
  python/avi/migrationtools/config_patch.py
  python/avi/migrationtools/f5_converter/clone_cross_tenant_obj.py
  python/avi/migrationtools/f5_converter/f5_converter.py
  python/avi/migrationtools/f5_discovery.py
  python/avi/migrationtools/gss_convertor/gss_convertor.py
  python/avi/migrationtools/netscaler_converter/netscaler_converter.py
  python/avi/migrationtools/netscaler_converter/test/netscaler_e2e_test.py
  python/avi/migrationtools/vs_filter.py
  python/avi/migrationtools/waf/avi_iwaf_vpatch.py
  python/avi/sdk/samples/alb_rules.py
  python/avi/sdk/samples/clone_vs.py
  python/avi/sdk/samples/clone_vs_segroup.py
  python/avi/sdk/samples/virtualservice_examples_api.py
  python/avi/sdk/samples/virtualservice_examples_saml_api.py
  python/avi/sdk/utils/app_logs/analyze_logs.py
  python/avi/sdk/utils/app_logs/fetch_logs.py
  python/version.py
Labels: AUTO PR, cla-not-required

#1528 Auto updated assets for java 21.1.1
  java/src/com/vmware/avi/sdk/model/CustomIpamDnsProfile.java
  java/src/com/vmware/avi/sdk/model/PortalFeatureOptIn.java
Labels: AUTO PR

#1527 Auto updated assets for docs 21.1.1
  docs/ALBServicesConfig/index.html
  docs/CustomIpamDnsProfile/index.html
Labels: AUTO PR

#1525 Auto updated assets for go models and clients 21.1.1
  go/models/custom_ip_a_m_dns_profile.go
  go/models/portal_feature_opt_in.go
Labels: AUTO PR

#1532 Removed travis from alb-sdk
  .travis.yml
Labels: cla-not-required

#1521 AV-119422 Added code owners for alb-sdk
  CODEOWNERS
Labels: cla-not-required

#1531 Remove travis from alb-sdk
  .travis.yml
Labels: cla-not-required

#1530 Auto updated assets for swagger 21.1.1
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1510 Auto updated assets for go models and clients eng
  go/models/connection_event_details.go
  go/models/custom_ip_a_m_dns_profile.go
  go/models/event_details.go
Labels: AUTO PR, cla-not-required

#1523 Auto updated assets for docs eng
  docs/CustomIpamDnsProfile/index.html
Labels: AUTO PR, cla-rejected

#1534 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/CustomIpamDnsProfile.java
Labels: AUTO PR, cla-not-required

#1539 Auto updated assets for swagger 21.1.1
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1538 Auto updated assets for swagger eng
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1536 Sync sdks for 21.1.1
  go/session/avisession_test.go
Labels: cla-not-required

#1540 Auto updated assets for go models and clients 21.1.1
  go/session/avisession_test.go
Labels: cla-not-required

#1535 AV-119422 Added code owners for alb-sdk v2
  CODEOWNERS
Labels: cla-not-required

#1541 Updated version for 21.1.1
  python/version.py
Labels: cla-not-required

#1546 Auto updated assets for docs eng
  docs/WafProfile/index.html
Labels: AUTO PR

#1547 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/WafConfig.java
  java/src/com/vmware/avi/sdk/model/WafContentTypeMapping.java
Labels: AUTO PR, cla-not-required

#1544 Auto updated assets for go models and clients eng
  go/models/waf_config.go
  go/models/waf_content_type_mapping.go
Labels: AUTO PR, cla-not-required

#1550 Auto updated assets for docs 20.1.7
  docs/Cloud/index.html
Labels: AUTO PR, cla-not-required

#1551 Auto updated assets for java 20.1.7
  java/src/com/vmware/avi/sdk/model/Cloud.java
Labels: AUTO PR, cla-not-required

#1548 Auto updated assets for go models and clients 20.1.7
  go/models/cloud.go
Labels: AUTO PR, cla-not-required

#1543 AV-119422 Added code owners for alb-sdk (#1521)
  CODEOWNERS
Labels: cla-not-required

#1553 Auto updated assets for go models and clients eng
  go/models/cloud.go
Labels: AUTO PR, cla-not-required

#1555 Auto updated assets for docs eng
  docs/Cloud/index.html
Labels: AUTO PR, cla-not-required

#1556 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/Cloud.java
Labels: AUTO PR, cla-not-required

#1564 Auto updated assets for swagger eng
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1565 Auto updated assets for swagger 21.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1566 Auto updated assets for java 21.1.2
  java/src/com/vmware/avi/sdk/AviAuthorizationInterceptor.java
Labels: AUTO PR, cla-not-required

#1568 Auto updated assets for java 20.1.7
  java/src/com/vmware/avi/sdk/AviAuthorizationInterceptor.java
Labels: AUTO PR, cla-not-required

#1570 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/AviAuthorizationInterceptor.java
Labels: AUTO PR, cla-not-required

#1562 added fix for VRO test failure
  java/pom.xml
  java/src/com/vmware/avi/sdk/AviAuthorizationInterceptor.java
Labels: cla-not-required

#1571 Auto updated assets for swagger 20.1.7
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1572 Auto updated assets for swagger eng
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1574 Auto updated assets for swagger 20.1.7
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1575 Auto updated assets for go models and clients eng
  go/models/portal_feature_opt_in.go
Labels: AUTO PR, cla-not-required

#1577 Auto updated assets for docs eng
  docs/ALBServicesConfig/index.html
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
  docs/Cloud/index.html
  docs/Image/index.html
  docs/ServiceEngine/index.html
  docs/ServiceEngineGroup/index.html
  docs/VirtualService/index.html
Labels: AUTO PR, cla-not-required

#1578 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/PortalFeatureOptIn.java
Labels: AUTO PR, cla-not-required

#1579 Auto updated assets for swagger 21.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1589 Auto updated assets for docs 20.1.7
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
  docs/PoolGroup/index.html
Labels: AUTO PR, cla-not-required

#1590 Auto updated assets for java 20.1.7
  java/src/com/vmware/avi/sdk/model/PoolGroup.java
  java/src/com/vmware/avi/sdk/model/PrimaryPool.java
Labels: AUTO PR, cla-not-required

#1587 Auto updated assets for go models and clients 20.1.7
  go/models/pool_group.go
  go/models/primary_pool.go
Labels: AUTO PR, cla-not-required

#1592 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/HardwareSecurityModule.java
  python/avi/sdk/utils/waf_policy/vdi_waf_policy.py
Labels: AUTO PR, cla-not-required

#1593 Auto updated assets for swagger 21.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1596 Auto updated assets for docs 20.1.7
  docs/Cloud/index.html
  docs/VIMgrSEVMRuntime/index.html
Labels: AUTO PR, cla-not-required

#1594 Auto updated assets for go models and clients 20.1.7
  go/models/g_c_p_configuration.go
  go/models/g_c_p_v_ip_routes.go
  go/models/v_i_mgr_s_e_vm_runtime.go
Labels: AUTO PR, cla-not-required

#1597 Auto updated assets for java 20.1.7
  java/src/com/vmware/avi/sdk/model/GCPConfiguration.java
  java/src/com/vmware/avi/sdk/model/GCPVIPRoutes.java
  java/src/com/vmware/avi/sdk/model/VIMgrSEVMRuntime.java
Labels: AUTO PR, cla-not-required
