Repository vmware/alb-sdk, pull requests merged in 2021-09, with the labels that each got.

#1599 Auto updated assets for swagger 20.1.7
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1601 Auto updated assets for swagger 21.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1604 Auto updated assets for docs 20.1.7
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/ServiceEngineGroup/index.html
  docs/VIMgrSEVMRuntime/index.html
  docs/VIMgrVcenterRuntime/index.html
Labels: AUTO PR

#1607 Auto updated assets for java 20.1.7
  java/src/com/vmware/avi/sdk/model/SeMgrEventDetails.java
Labels: AUTO PR, cla-not-required

#1606 Auto updated assets for docs 20.1.7
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/VIMgrVcenterRuntime/index.html
Labels: AUTO PR, cla-not-required

#1602 Auto updated assets for go models and clients 20.1.7
  go/models/cluster_h_a_config.go
  go/models/event_details.go
  go/models/placement_scope_config.go
  go/models/se_mgr_event_details.go
  go/models/v_i_mgr_s_e_vm_runtime.go
  go/models/vcenter_cluster_details.go
Labels: AUTO PR, cla-not-required

#1610 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/ServiceEngineGroup/index.html
  docs/VIMgrSEVMRuntime/index.html
  docs/VIMgrVcenterRuntime/index.html
Labels: AUTO PR, cla-not-required

#1611 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/ClusterHAConfig.java
  java/src/com/vmware/avi/sdk/model/EventDetails.java
  java/src/com/vmware/avi/sdk/model/PlacementScopeConfig.java
  java/src/com/vmware/avi/sdk/model/VIMgrSEVMRuntime.java
  java/src/com/vmware/avi/sdk/model/VcenterClusterDetails.java
Labels: AUTO PR, cla-not-required

#1612 Auto updated assets for go models and clients 21.1.2
  go/models/cloud.go
Labels: AUTO PR, cla-not-required

#1614 Auto updated assets for docs 21.1.2
  docs/Cloud/index.html
Labels: AUTO PR, cla-not-required

#1615 Auto updated assets for java 21.1.2
  java/src/com/vmware/avi/sdk/model/Cloud.java
Labels: AUTO PR, cla-not-required

#1608 Auto updated assets for go models and clients eng
  go/models/cluster_h_a_config.go
  go/models/event_details.go
  go/models/placement_scope_config.go
  go/models/v_i_mgr_s_e_vm_runtime.go
  go/models/vcenter_cluster_details.go
Labels: AUTO PR, cla-not-required

#1618 Auto updated assets for docs 20.1.7
  docs/CloudProperties/index.html
  docs/ControllerProperties/index.html
  docs/PoolGroup/index.html
Labels: AUTO PR, cla-not-required

#1616 Auto updated assets for go models and clients 20.1.7
  go/models/controller_properties.go
  go/models/pool_group.go
Labels: AUTO PR, cla-not-required

#1619 Auto updated assets for java 20.1.7
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/PoolGroup.java
Labels: AUTO PR, cla-not-required

#1620 Auto updated assets for go models and clients eng
  go/models/pool_group.go
  go/models/primary_pool.go
  go/models/scheduled_scaling.go
  go/models/server_auto_scale_in_info.go
  go/models/server_auto_scale_out_info.go
  go/models/server_auto_scale_policy.go
  go/models/v_i_mgr_s_e_vm_runtime.go
Labels: AUTO PR, cla-not-required

#1622 Auto updated assets for docs eng
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
  docs/Image/index.html
  docs/PoolGroup/index.html
  docs/ServerAutoScalePolicy/index.html
  docs/VIMgrSEVMRuntime/index.html
Labels: AUTO PR, cla-not-required

#1623 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/PoolGroup.java
  java/src/com/vmware/avi/sdk/model/PrimaryPool.java
  java/src/com/vmware/avi/sdk/model/ScheduledScaling.java
  java/src/com/vmware/avi/sdk/model/ServerAutoScaleInInfo.java
  java/src/com/vmware/avi/sdk/model/ServerAutoScaleOutInfo.java
  java/src/com/vmware/avi/sdk/model/ServerAutoScalePolicy.java
  java/src/com/vmware/avi/sdk/model/VIMgrSEVMRuntime.java
Labels: AUTO PR, cla-not-required

#1624 Auto updated assets for go models and clients 21.1.2
  go/models/pool_group.go
  go/models/primary_pool.go
  go/models/v_i_mgr_s_e_vm_runtime.go
Labels: AUTO PR, cla-not-required

#1626 Auto updated assets for docs 21.1.2
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
  docs/PoolGroup/index.html
  docs/VIMgrSEVMRuntime/index.html
Labels: AUTO PR, cla-not-required

#1627 Auto updated assets for java 21.1.2
  java/src/com/vmware/avi/sdk/model/PoolGroup.java
  java/src/com/vmware/avi/sdk/model/PrimaryPool.java
  java/src/com/vmware/avi/sdk/model/VIMgrSEVMRuntime.java
Labels: AUTO PR, cla-not-required

#1486 Auto updated root sdk files 20.1.7
  LICENSE
Labels: AUTO PR, cla-not-required

#1631 Auto updated assets for java 20.1.7
  java/pom.xml
Labels: AUTO PR, cla-not-required

#1632 Auto updated assets for swagger eng
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1635 Auto updated assets for java 21.1.2
  java/pom.xml
Labels: AUTO PR, cla-not-required

#1636 Auto updated assets for swagger 20.1.7
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1637 Auto updated assets for swagger eng
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1640 Auto updated assets for docs 21.1.2
  docs/Cloud/index.html
Labels: AUTO PR, cla-not-required

#1641 Auto updated assets for java 21.1.2
  java/src/com/vmware/avi/sdk/model/GCPConfiguration.java
  java/src/com/vmware/avi/sdk/model/GCPVIPRoutes.java
Labels: AUTO PR, cla-not-required

#1638 Auto updated assets for go models and clients 21.1.2
  go/models/g_c_p_configuration.go
  go/models/g_c_p_v_ip_routes.go
Labels: AUTO PR, cla-not-required

#1558 Auto updated assets for python 21.1.2
  python/version.py
Labels: AUTO PR, cla-not-required

#1643 Auto updated assets for go models and clients eng
  go/models/g_c_p_configuration.go
  go/models/g_c_p_v_ip_routes.go
Labels: AUTO PR, cla-not-required

#1645 Auto updated assets for docs eng
  docs/Cloud/index.html
Labels: AUTO PR, cla-not-required

#1646 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/GCPConfiguration.java
  java/src/com/vmware/avi/sdk/model/GCPVIPRoutes.java
Labels: AUTO PR, cla-not-required

#1647 Auto updated assets for swagger 21.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1649 Auto updated assets for go models and clients eng
  go/models/scheduled_scaling.go
Labels: AUTO PR, cla-not-required

#1651 Auto updated assets for docs eng
  docs/ServerAutoScalePolicy/index.html
Labels: AUTO PR, cla-not-required

#1633 Auto updated assets for python eng
  python/avi/sdk/utils/waf_policy/vdi_waf_policy.py
  python/version.py
Labels: AUTO PR, cla-not-required

#1655 Auto updated assets for docs 20.1.7
  docs/Alert/index.html
  docs/ServiceEngineGroup/index.html
Labels: AUTO PR, cla-not-required

#1656 Auto updated assets for java 20.1.7
  java/src/com/vmware/avi/sdk/model/ClusterHAConfig.java
  java/src/com/vmware/avi/sdk/model/NsxtClusters.java
  java/src/com/vmware/avi/sdk/model/PlacementScopeConfig.java
  java/src/com/vmware/avi/sdk/model/SeMgrEventDetails.java
Labels: AUTO PR, cla-not-required

#1653 Auto updated assets for go models and clients 20.1.7
  go/models/cluster_h_a_config.go
  go/models/nsxt_clusters.go
  go/models/placement_scope_config.go
  go/models/se_mgr_event_details.go
Labels: AUTO PR, cla-not-required

#1658 Auto updated assets for swagger 21.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1662 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/Cloud/index.html
  docs/VIMgrVcenterRuntime/index.html
Labels: AUTO PR, cla-not-required

#1663 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/EventDetails.java
  java/src/com/vmware/avi/sdk/model/VcenterImageDetails.java
  java/src/com/vmware/avi/sdk/model/vCenterConfiguration.java
Labels: AUTO PR, cla-not-required

#1660 Auto updated assets for go models and clients eng
  go/models/event_details.go
  go/models/v_center_configuration.go
  go/models/vcenter_image_details.go
Labels: AUTO PR, cla-not-required

#1664 Auto updated assets for swagger 21.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1666 Auto updated assets for swagger 21.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1630 Auto updated assets for python 20.1.7
  python/version.py
Labels: AUTO PR, cla-not-required

#1668 Auto updated assets for go models and clients eng
  go/models/cluster_h_a_config.go
  go/models/controller_properties.go
  go/models/http_application_profile.go
  go/models/nsxt_clusters.go
  go/models/placement_scope_config.go
  go/models/se_mgr_event_details.go
Labels: AUTO PR, cla-not-required

#1670 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/ApplicationProfile/index.html
  docs/CloudProperties/index.html
  docs/ControllerProperties/index.html
  docs/ServiceEngineGroup/index.html
  docs/VIMgrVcenterRuntime/index.html
Labels: AUTO PR, cla-not-required

#1671 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/ClusterHAConfig.java
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/HTTPApplicationProfile.java
  java/src/com/vmware/avi/sdk/model/NsxtClusters.java
  java/src/com/vmware/avi/sdk/model/PlacementScopeConfig.java
  java/src/com/vmware/avi/sdk/model/SeMgrEventDetails.java
Labels: AUTO PR, cla-not-required

#1672 Auto updated assets for go models and clients 21.1.2
  go/models/nsxt_clusters.go
  go/models/placement_scope_config.go
Labels: AUTO PR, cla-not-required

#1674 Auto updated assets for docs 21.1.2
  docs/ServiceEngineGroup/index.html
Labels: AUTO PR, cla-not-required

#1675 Auto updated assets for java 21.1.2
  java/src/com/vmware/avi/sdk/model/NsxtClusters.java
  java/src/com/vmware/avi/sdk/model/PlacementScopeConfig.java
Labels: AUTO PR, cla-not-required

#1678 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
Labels: AUTO PR, cla-not-required

#1681 Auto updated assets for docs 21.1.2
  docs/ApplicationProfile/index.html
Labels: AUTO PR, cla-not-required

#1682 Auto updated assets for java 21.1.2
  java/src/com/vmware/avi/sdk/model/HTTPApplicationProfile.java
Labels: AUTO PR, cla-not-required

#1679 Auto updated assets for go models and clients 21.1.2
  go/models/http_application_profile.go
Labels: AUTO PR, cla-not-required

#1685 Auto updated assets for docs 20.1.7
  docs/AnalyticsProfile/index.html
Labels: AUTO PR, cla-not-required

#1686 Auto updated assets for java 20.1.7
  java/src/com/vmware/avi/sdk/model/SensitiveLogProfile.java
Labels: AUTO PR, cla-not-required

#1683 Auto updated assets for go models and clients 20.1.7
  go/models/sensitive_log_profile.go
Labels: AUTO PR, cla-not-required

#1688 Auto updated assets for go models and clients eng
  go/models/debug_service_engine.go
  go/models/http_hdr_value.go
  go/models/s_s_l_client_request_header.go
Labels: AUTO PR, cla-not-required

#1690 Auto updated assets for docs eng
  docs/ApplicationProfile/index.html
  docs/DebugServiceEngine/index.html
  docs/HTTPPolicySet/index.html
Labels: AUTO PR, cla-not-required

#1692 Auto updated assets for swagger 21.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1691 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/DebugServiceEngine.java
  java/src/com/vmware/avi/sdk/model/HTTPHdrValue.java
  java/src/com/vmware/avi/sdk/model/SSLClientRequestHeader.java
Labels: AUTO PR, cla-not-required

#1693 Auto updated assets for swagger eng
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1694 Auto updated assets for swagger 21.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1695 Auto updated assets for go models and clients 21.1.2
  go/models/sensitive_log_profile.go
Labels: AUTO PR, cla-not-required

#1697 Auto updated assets for docs 21.1.2
  docs/AnalyticsProfile/index.html
Labels: AUTO PR, cla-not-required

#1698 Auto updated assets for java 21.1.2
  java/src/com/vmware/avi/sdk/model/SensitiveLogProfile.java
Labels: AUTO PR, cla-not-required

#1702 Auto updated assets for docs eng
  docs/AnalyticsProfile/index.html
Labels: AUTO PR, cla-not-required

#1703 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/SensitiveLogProfile.java
Labels: AUTO PR, cla-not-required

#1700 Auto updated assets for go models and clients eng
  go/models/sensitive_log_profile.go
Labels: AUTO PR, cla-not-required

#1699 Update README.md to remove travis
  README.md
Labels: cla-not-required

#1249 Update README.md
  go/README.md
  java/README.md
  python/avi/sdk/README.md
Labels: DO NOT MERGE

#1707 Delete .travis.yml
  .travis.yml
Labels: cla-not-required

#1709 Auto updated assets for go models and clients eng
  go/README.md
Labels: AUTO PR, cla-not-required

#1712 Auto updated assets for java eng
  java/README.md
Labels: AUTO PR, cla-not-required

#1718 Auto updated assets for docs eng
  docs/BotMapping/index.html
  docs/SystemLimits/index.html
  docs/WafApplicationSignatureProvider/index.html
  docs/WafCRS/index.html
  docs/WafPolicy/index.html
  docs/WafPolicyPSMGroup/index.html
  docs/WafProfile/index.html
Labels: AUTO PR, cla-not-required

#1716 Auto updated assets for go models and clients eng
  go/README.md
  go/models/bot_mapping_rule.go
  go/models/controller_limits.go
  go/models/w_a_f_limits.go
  go/models/waf_application_signatures.go
  go/models/waf_config.go
  go/models/waf_p_s_m_location.go
  go/models/waf_p_s_m_rule.go
  go/models/waf_policy_allowlist.go
  go/models/waf_policy_p_s_m_group.go
  go/models/waf_positive_security_model.go
  go/models/waf_profile.go
  go/models/waf_rule.go
  go/models/waf_rule_group.go
Labels: AUTO PR, cla-not-required

#1719 Auto updated assets for java eng
  java/README.md
  java/src/com/vmware/avi/sdk/model/BotMappingRule.java
  java/src/com/vmware/avi/sdk/model/ControllerLimits.java
  java/src/com/vmware/avi/sdk/model/WAFLimits.java
  java/src/com/vmware/avi/sdk/model/WafApplicationSignatures.java
  java/src/com/vmware/avi/sdk/model/WafConfig.java
  java/src/com/vmware/avi/sdk/model/WafPSMLocation.java
  java/src/com/vmware/avi/sdk/model/WafPSMRule.java
  java/src/com/vmware/avi/sdk/model/WafPolicyAllowlist.java
  java/src/com/vmware/avi/sdk/model/WafPolicyPSMGroup.java
  java/src/com/vmware/avi/sdk/model/WafPositiveSecurityModel.java
  java/src/com/vmware/avi/sdk/model/WafProfile.java
  java/src/com/vmware/avi/sdk/model/WafRule.java
  java/src/com/vmware/avi/sdk/model/WafRuleGroup.java
Labels: AUTO PR, cla-not-required

#1722 Auto updated assets for docs 21.1.2
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/VIMgrVcenterRuntime/index.html
Labels: AUTO PR, cla-not-required

#1720 Auto updated assets for go models and clients 21.1.2
  go/models/event_details.go
  go/models/sec_mgr_u_a_event_details.go
Labels: AUTO PR, cla-not-required

#1723 Auto updated assets for java 21.1.2
  java/src/com/vmware/avi/sdk/model/EventDetails.java
  java/src/com/vmware/avi/sdk/model/HardwareSecurityModule.java
  java/src/com/vmware/avi/sdk/model/SecMgrUAEventDetails.java
Labels: AUTO PR, cla-not-required

#1724 Auto updated assets for swagger 20.1.8
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1725 Auto updated assets for swagger eng
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1726 Auto updated assets for swagger 21.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1730 Auto updated assets for swagger 20.1.8
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1731 Auto updated assets for go models and clients eng
  go/models/app_signature_config.go
  go/models/case_config.go
  go/models/ip_reputation_config.go
  go/models/user_agent_d_b_config.go
  go/models/waf_crs_config.go
Labels: AUTO PR, cla-not-required

#1733 Auto updated assets for docs eng
  docs/ALBServicesConfig/index.html
Labels: AUTO PR, cla-not-required

#1734 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/AppSignatureConfig.java
  java/src/com/vmware/avi/sdk/model/CaseConfig.java
  java/src/com/vmware/avi/sdk/model/IpReputationConfig.java
  java/src/com/vmware/avi/sdk/model/UserAgentDBConfig.java
  java/src/com/vmware/avi/sdk/model/WafCrsConfig.java
Labels: AUTO PR, cla-not-required
