Repository vmware/alb-sdk, pull requests merged in 2022-02, with the labels that each got.

#1965 Auto updated assets for swagger 20.1.8
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1966 Auto updated assets for docs 20.1.8
  docs/Alert/index.html
Labels: AUTO PR

#1968 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/DebugVirtualService/index.html
Labels: AUTO PR, cla-not-required

#1969 Auto updated assets for swagger 21.1.4
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1858 Auto updated assets for python 20.1.8
  python/avi/migrationtools/f5_converter/persistence_converter.py
Labels: AUTO PR, cla-not-required

#1808 Auto updated assets for java 20.1.8
  java/src/com/vmware/avi/sdk/AviAuthorizationInterceptor.java
  java/src/com/vmware/avi/sdk/AviCredentials.java
  java/src/com/vmware/avi/sdk/AviRestUtils.java
  java/src/com/vmware/avi/sdk/model/ALBServicesFileUpload.java
  java/src/com/vmware/avi/sdk/model/AnalyticsProfile.java
  java/src/com/vmware/avi/sdk/model/AppSignatureConfig.java
  java/src/com/vmware/avi/sdk/model/ClientLogConfiguration.java
  java/src/com/vmware/avi/sdk/model/ClusterNode.java
  java/src/com/vmware/avi/sdk/model/ControllerInterface.java
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/DnsInfo.java
  java/src/com/vmware/avi/sdk/model/EventDetails.java
  java/src/com/vmware/avi/sdk/model/FailActionHTTPRedirect.java
  java/src/com/vmware/avi/sdk/model/FullClientLogs.java
  java/src/com/vmware/avi/sdk/model/GslbGeoDbFile.java
  java/src/com/vmware/avi/sdk/model/GslbThirdPartySite.java
  java/src/com/vmware/avi/sdk/model/HSMAwsCloudHsm.java
  java/src/com/vmware/avi/sdk/model/HTTPApplicationProfile.java
  java/src/com/vmware/avi/sdk/model/Network.java
  java/src/com/vmware/avi/sdk/model/NsxtSIEndpointDetails.java
  java/src/com/vmware/avi/sdk/model/NsxtSIPolicyDetails.java
  java/src/com/vmware/avi/sdk/model/NsxtSIRuleDetails.java
  java/src/com/vmware/avi/sdk/model/NsxtSIServiceDetails.java
  java/src/com/vmware/avi/sdk/model/OCSPResponseInfo.java
  java/src/com/vmware/avi/sdk/model/PKIProfile.java
  java/src/com/vmware/avi/sdk/model/Pool.java
  java/src/com/vmware/avi/sdk/model/PortalFeatureOptIn.java
  java/src/com/vmware/avi/sdk/model/ProactiveSupportDefaults.java
  java/src/com/vmware/avi/sdk/model/SAMLSPConfig.java
  java/src/com/vmware/avi/sdk/model/SSLKeyAndCertificate.java
  java/src/com/vmware/avi/sdk/model/SSLProfile.java
  java/src/com/vmware/avi/sdk/model/SeRuntimeProperties.java
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
  java/src/com/vmware/avi/sdk/model/SystemConfiguration.java
  java/src/com/vmware/avi/sdk/model/Tier1LogicalRouterInfo.java
  java/src/com/vmware/avi/sdk/model/VipAutoscaleZones.java
  java/src/com/vmware/avi/sdk/model/VirtualService.java
  java/src/com/vmware/avi/sdk/model/WafApplicationSignatureAppVersion.java
  java/src/com/vmware/avi/sdk/model/WafApplicationSignatureProvider.java
  java/src/com/vmware/avi/sdk/model/WafApplicationSignatures.java
  java/src/com/vmware/avi/sdk/model/WafExcludeListEntry.java
  java/src/com/vmware/avi/sdk/model/WafRule.java
Labels: AUTO PR, cla-not-required

#1970 Update version.py
  python/version.py
Labels: cla-not-required

#1971 Update AviRestUtils.java
  java/src/com/vmware/avi/sdk/AviRestUtils.java
Labels: cla-not-required

#1978 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/DebugVirtualService/index.html
Labels: AUTO PR, cla-not-required

#1981 Auto updated assets for docs 21.1.4
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/Image/index.html
  docs/LicenseStatus/index.html
  docs/VIMgrVcenterRuntime/index.html
Labels: AUTO PR, cla-not-required

#1982 Auto updated assets for java 21.1.4
  java/src/com/vmware/avi/sdk/model/CentralLicenseRefreshDetails.java
  java/src/com/vmware/avi/sdk/model/CentralLicenseSubscriptionDetails.java
  java/src/com/vmware/avi/sdk/model/EventDetails.java
  java/src/com/vmware/avi/sdk/model/LicenseServiceUpdate.java
  java/src/com/vmware/avi/sdk/model/LicenseStatus.java
  java/src/com/vmware/avi/sdk/model/OrgServiceUnits.java
Labels: AUTO PR, cla-not-required

#1984 Auto updated assets for swagger 20.1.9
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#1987 Auto updated assets for docs eng
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/GeoDB/index.html
  docs/Image/index.html
  docs/LicenseStatus/index.html
  docs/NetworkProfile/index.html
  docs/SystemLimits/index.html
  docs/VIMgrVcenterRuntime/index.html
  docs/WafProfile/index.html
  docs/metrics_query.html
Labels: AUTO PR, cla-not-required

#1988 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/CentralLicenseRefreshDetails.java
  java/src/com/vmware/avi/sdk/model/CentralLicenseSubscriptionDetails.java
  java/src/com/vmware/avi/sdk/model/DsrProfile.java
  java/src/com/vmware/avi/sdk/model/EventDetails.java
  java/src/com/vmware/avi/sdk/model/LicenseServiceUpdate.java
  java/src/com/vmware/avi/sdk/model/LicenseStatus.java
  java/src/com/vmware/avi/sdk/model/OrgServiceUnits.java
  java/src/com/vmware/avi/sdk/model/WAFLimits.java
  java/src/com/vmware/avi/sdk/model/WafConfig.java
Labels: AUTO PR, cla-not-required

#1979 Auto updated assets for go models and clients 21.1.4
  go/models/central_license_refresh_details.go
  go/models/central_license_subscription_details.go
  go/models/event_details.go
  go/models/license_service_update.go
  go/models/license_status.go
  go/models/org_service_units.go
Labels: AUTO PR, cla-not-required

#1992 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/UserAccountProfile.java
  java/src/com/vmware/avi/sdk/model/UserActivity.java
Labels: AUTO PR, cla-not-required
