Repository vmware/alb-sdk, pull requests merged in 2022-09, with the labels that each got.

#2343 AV-153408: Added minor changes in the github action for Java SDK release.
  .github/workflows/release.yml
Labels: cla-not-required

#2340 AV-153408: Added changes in github action for Java SDK jar release.
  .github/workflows/release.yml
Labels: Cherry-pick, cla-not-required

#2339 AV-153408: Added changes in github action for Java SDK jar release.
  .github/workflows/release.yml
Labels: Cherry-pick, cla-not-required

#2345 Auto updated assets for docs 22.1.2
  docs/SystemConfiguration/index.html
Labels: AUTO PR, cla-not-required

#2350 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/AnalyticsProfile/index.html
  docs/ApplicationProfile/index.html
  docs/CloudProperties/index.html
  docs/ServiceEngineGroup/index.html
  docs/ServiceEngineGroupInventory/index.html
  docs/SystemConfiguration/index.html
  docs/VIMgrHostRuntime/index.html
  docs/metrics_query.html
Labels: AUTO PR, cla-not-required

#2355 Auto updated assets for java 21.1.6
  java/src/com/vmware/avi/sdk/AviApi.java
  java/src/com/vmware/avi/sdk/AviRestUtils.java
  java/src/com/vmware/avi/sdk/model/AWSLogin.java
  java/src/com/vmware/avi/sdk/model/Cloud.java
  java/src/com/vmware/avi/sdk/model/EventDetails.java
  java/src/com/vmware/avi/sdk/model/EventGenParams.java
  java/src/com/vmware/avi/sdk/model/OpenstackLogin.java
  java/src/com/vmware/avi/sdk/model/RediscoverVcenterParam.java
  java/src/com/vmware/avi/sdk/model/SAMLSPConfig.java
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
  java/src/com/vmware/avi/sdk/model/VIAdminCredentials.java
  java/src/com/vmware/avi/sdk/model/VIControllerVnicInfo.java
  java/src/com/vmware/avi/sdk/model/VICreateSEReq.java
  java/src/com/vmware/avi/sdk/model/VIDeleteNetworkFilter.java
  java/src/com/vmware/avi/sdk/model/VIDeleteSEReq.java
  java/src/com/vmware/avi/sdk/model/VIFaultInjection.java
  java/src/com/vmware/avi/sdk/model/VIGuestvNicIPAddr.java
  java/src/com/vmware/avi/sdk/model/VIMgrControllerRuntime.java
  java/src/com/vmware/avi/sdk/model/VIMgrControllerRuntimeApiResponse.java
  java/src/com/vmware/avi/sdk/model/VIMgrDCRuntime.java
  java/src/com/vmware/avi/sdk/model/VIMgrDCRuntimeApiResponse.java
  java/src/com/vmware/avi/sdk/model/VIMgrInterestedEntity.java
  java/src/com/vmware/avi/sdk/model/VIMgrVcenterRuntime.java
  java/src/com/vmware/avi/sdk/model/VIMgrVcenterRuntimeApiResponse.java
  java/src/com/vmware/avi/sdk/model/VIRetrievePGNames.java
  java/src/com/vmware/avi/sdk/model/VISeVmIpConfParams.java
  java/src/com/vmware/avi/sdk/model/VISeVmOvaParams.java
  java/src/com/vmware/avi/sdk/model/VISetMgmtIpSEReq.java
  java/src/com/vmware/avi/sdk/model/VISetvNicNwReq.java
  java/src/com/vmware/avi/sdk/model/VIVmVnicInfo.java
  java/src/com/vmware/avi/sdk/model/VcenterCloudStatusReq.java
  java/src/com/vmware/avi/sdk/model/VcenterImageDetails.java
  java/src/com/vmware/avi/sdk/model/VcenterInventoryDiagReq.java
  java/src/com/vmware/avi/sdk/model/VcenterLogin.java
  java/src/com/vmware/avi/sdk/model/vCenterConfiguration.java
Labels: AUTO PR, cla-not-required

#2351 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/AviApi.java
  java/src/com/vmware/avi/sdk/AviRestUtils.java
  java/src/com/vmware/avi/sdk/model/AdminAuthConfiguration.java
  java/src/com/vmware/avi/sdk/model/ApplicationProfile.java
  java/src/com/vmware/avi/sdk/model/CC_AgentProperties.java
  java/src/com/vmware/avi/sdk/model/ClientLogStreamingConfig.java
  java/src/com/vmware/avi/sdk/model/HTTPApplicationProfile.java
  java/src/com/vmware/avi/sdk/model/L4SSLApplicationProfile.java
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
  java/src/com/vmware/avi/sdk/model/VcenterQuarantinedHostParams.java
  java/src/com/vmware/avi/sdk/model/WafLog.java
Labels: AUTO PR, cla-not-required

#2357 Auto updated assets for docs 22.1.2
  docs/ApplicationProfile/index.html
Labels: AUTO PR, cla-not-required

#2346 Auto updated assets for java 22.1.2
  java/pom.xml
  java/src/com/vmware/avi/sdk/AviApi.java
  java/src/com/vmware/avi/sdk/AviRestUtils.java
  java/src/com/vmware/avi/sdk/model/AdminAuthConfiguration.java
  java/src/com/vmware/avi/sdk/model/ApplicationProfile.java
  java/src/com/vmware/avi/sdk/model/L4SSLApplicationProfile.java
Labels: AUTO PR, cla-not-required

#2347 Auto updated assets for go models and clients eng
  go/models/admin_auth_configuration.go
  go/models/application_profile.go
  go/models/c_c_agent_properties.go
  go/models/client_log_streaming_config.go
  go/models/http_application_profile.go
  go/models/l4_s_slapplication_profile.go
  go/models/service_engine_group.go
  go/models/vcenter_quarantined_host_params.go
  go/models/waf_log.go
Labels: AUTO PR, cla-not-required

#2359 Auto updated assets for go models and clients eng
  go/models/query_match.go
  go/models/waf_policy.go
  go/models/waf_policy_required_data_file.go
Labels: AUTO PR, cla-not-required

#2362 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/QueryMatch.java
  java/src/com/vmware/avi/sdk/model/WafPolicyRequiredDataFile.java
Labels: AUTO PR, cla-not-required

#2336 Auto updated assets for go models and clients 22.1.2
  go/models/application_profile.go
  go/models/l4_s_slapplication_profile.go
  go/session/avisession.go
  go/session/avisession_test.go
Labels: AUTO PR, cla-not-required

#2365 Auto updated assets for java eng
  java/pom.xml
  java/src/com/vmware/avi/sdk/AviApi.java
Labels: AUTO PR, cla-not-required

#2368 Auto updated assets for java 22.1.2
  java/pom.xml
  java/src/com/vmware/avi/sdk/AviApi.java
Labels: AUTO PR, cla-not-required

#2369 Auto updated assets for swagger eng
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#2352 Auto updated assets for go models and clients 21.1.6
  go/clients/avi_client.go
  go/clients/vimgrcontrollerruntime_client.go
  go/clients/vimgrdcruntime_client.go
  go/clients/vimgrvcenterruntime_client.go
  go/models/a_w_s_login.go
  go/models/cloud.go
  go/models/event_details.go
  go/models/event_gen_params.go
  go/models/event_log.go
  go/models/openstack_login.go
  go/models/rediscover_vcenter_param.go
  go/models/s_a_m_l_s_p_config.go
  go/models/service_engine_group.go
  go/models/v_center_configuration.go
  go/models/v_i_admin_credentials.go
  go/models/v_i_controller_vnic_info.go
  go/models/v_i_create_s_e_req.go
  go/models/v_i_fault_injection.go
  go/models/v_i_guestv_nic_ip_addr.go
  go/models/v_i_mgr_controller_runtime.go
  go/models/v_i_mgr_controller_runtime_api_response.go
  go/models/v_i_mgr_d_c_runtime.go
  go/models/v_i_mgr_d_c_runtime_api_response.go
  go/models/v_i_mgr_interested_entity.go
  go/models/v_i_mgr_vcenter_runtime.go
  go/models/v_i_mgr_vcenter_runtime_api_response.go
  go/models/v_i_retrieve_p_g_names.go
  go/models/v_i_se_vm_ip_conf_params.go
  go/models/v_i_se_vm_ova_params.go
  go/models/v_i_set_mgmt_ip_s_e_req.go
  go/models/v_i_setv_nic_nw_req.go
  go/models/v_i_vm_vnic_info.go
  go/models/v_idelete_network_filter.go
  go/models/v_idelete_s_e_req.go
  go/models/vcenter_cloud_status_req.go
  go/models/vcenter_image_details.go
  go/models/vcenter_inventory_diag_req.go
  go/models/vcenter_login.go
  go/session/avisession.go
  go/session/avisession_test.go
Labels: AUTO PR, cla-not-required

#2366 AV-153926: Fixed Java SDK update API failure.
  java/pom.xml
  java/src/com/vmware/avi/sdk/AviApi.java
Labels: cla-not-required

#2372 Auto updated assets for java 22.1.2
  java/pom.xml
Labels: AUTO PR, cla-not-required

#2374 Auto updated assets for java eng
  java/pom.xml
Labels: AUTO PR, cla-not-required

#2375 Auto updated assets for go models and clients 22.1.2
  go/models/http_application_profile.go
Labels: AUTO PR, cla-not-required

#2377 Auto updated assets for docs 22.1.2
  docs/ApplicationProfile/index.html
Labels: AUTO PR, cla-not-required

#2378 Auto updated assets for java 22.1.2
  java/src/com/vmware/avi/sdk/model/HTTPApplicationProfile.java
Labels: AUTO PR, cla-not-required

#2380 Auto updated assets for go models and clients 21.1.6
  go/models/c_c_agent_properties.go
  go/models/vcenter_quarantined_host_params.go
Labels: AUTO PR, cla-not-required

#2383 Auto updated assets for docs 21.1.6
  docs/CloudProperties/index.html
  docs/VIMgrHostRuntime/index.html
Labels: AUTO PR, cla-not-required

#2384 Auto updated assets for java 21.1.6
  java/pom.xml
  java/src/com/vmware/avi/sdk/AviApi.java
  java/src/com/vmware/avi/sdk/model/CC_AgentProperties.java
  java/src/com/vmware/avi/sdk/model/VcenterQuarantinedHostParams.java
Labels: AUTO PR, cla-not-required

#2370 AV-152818: Added readme file for NSX-T LB to ALB Migration tool
  python/avi/migrationtools/README.md
  python/avi/migrationtools/nsxt_converter/NSX-T_to_Avi_Migration_Tool_-_How_To_Guide.pdf
  python/avi/migrationtools/nsxt_converter/README.md
Labels: cla-not-required

#2390 Auto updated assets for swagger 21.1.6
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#2396 Auto updated assets for docs 22.1.2
  docs/NsxtSegmentRuntime/index.html
Labels: AUTO PR, cla-not-required

#2394 Auto updated assets for go models and clients 22.1.2
  go/models/nsxt_segment_runtime.go
Labels: AUTO PR, cla-not-required

#2397 Auto updated assets for java 22.1.2
  java/src/com/vmware/avi/sdk/model/NsxtSegmentRuntime.java
Labels: AUTO PR, cla-not-required

#2387 AV-152818: Readme file formatting
  python/avi/migrationtools/nsxt_converter/README.md
Labels: cla-not-required

#2398 Auto updated assets for go models and clients eng
  go/models/waf_data_file.go
  go/models/waf_policy_required_data_file.go
Labels: AUTO PR, cla-not-required

#2400 Auto updated assets for docs eng
  docs/WafPolicy/index.html
  docs/WafProfile/index.html
Labels: AUTO PR, cla-not-required

#2401 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/OverallInfo.java
  java/src/com/vmware/avi/sdk/model/WafDataFile.java
  java/src/com/vmware/avi/sdk/model/WafPolicyRequiredDataFile.java
Labels: AUTO PR, cla-not-required

#2407 Auto updated assets for go models and clients eng
  go/models/virtual_service.go
Labels: AUTO PR, cla-not-required

#2409 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/VirtualService/index.html
Labels: AUTO PR, cla-not-required

#2344 Auto updated assets for python 22.1.2
  python/avi/migrationtools/ansible/ansible_config_converter.py
  python/avi/migrationtools/ansible/ansible_constant.py
  python/avi/migrationtools/ansible/avi_config_to_ansible.py
  python/avi/migrationtools/avi_migration_utils.py
  python/avi/migrationtools/avi_orphan_object.py
  python/avi/migrationtools/config_patch.py
  python/avi/migrationtools/f5_converter/command_status.yaml
  python/avi/migrationtools/f5_converter/conversion_util.py
  python/avi/migrationtools/f5_converter/f5_config_converter.py
  python/avi/migrationtools/f5_converter/monitor_converter.py
  python/avi/migrationtools/f5_converter/profile_converter.py
  python/avi/migrationtools/f5_converter/test/patch.yaml
  python/avi/migrationtools/f5_converter/vs_converter.py
  python/avi/migrationtools/nsxt_converter/__init__.py
  python/avi/migrationtools/nsxt_converter/command_status.yaml
  python/avi/migrationtools/nsxt_converter/conversion_util.py
  python/avi/migrationtools/nsxt_converter/install_nsx_dependencies.py
  python/avi/migrationtools/nsxt_converter/nsxt_config_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/persistant_converter.py
  python/avi/migrationtools/nsxt_converter/policy_converter.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/rollback.py
  python/avi/migrationtools/nsxt_converter/test/default_params.json
  python/avi/migrationtools/nsxt_converter/test/test_migrationtool.py
  python/avi/migrationtools/nsxt_converter/traffic_cutover.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
  python/avi/migrationtools/setup.py
  python/avi/sdk/avi_api.py
  python/avi/sdk/samples/virtualservice_examples_api.py
  python/avi/sdk/samples/virtualservice_examples_saml_api.py
  python/avi/sdk/samples/virtualservice_examples_sdk.py
  python/version.py
Labels: AUTO PR, cla-not-required

#2413 Auto updated assets for docs 21.1.6
  docs/metrics_query.html
Labels: AUTO PR, cla-not-required

#2403 Auto updated assets for python 21.1.6
  python/avi/sdk/avi_api.py
Labels: AUTO PR, cla-not-required

#2415 Auto updated assets for java 22.1.2
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
Labels: AUTO PR, cla-not-required

#2417 Auto updated assets for python eng
  python/avi/migrationtools/ansible/ansible_config_converter.py
  python/avi/migrationtools/ansible/ansible_constant.py
  python/avi/migrationtools/ansible/avi_config_to_ansible.py
  python/avi/migrationtools/config_patch.py
  python/avi/migrationtools/f5_converter/command_status.yaml
  python/avi/migrationtools/f5_converter/conversion_util.py
  python/avi/migrationtools/f5_converter/f5_config_converter.py
  python/avi/migrationtools/f5_converter/profile_converter.py
  python/avi/migrationtools/f5_converter/vs_converter.py
  python/avi/migrationtools/lib/__init__.py
  python/avi/migrationtools/lib/nsx_policy_python_sdk-4.0.0.1.0-py2.py3-none-any.whl
  python/avi/migrationtools/lib/nsx_python_sdk-4.0.0.1.0-py2.py3-none-any.whl
  python/avi/migrationtools/lib/vapi_common_client-2.29.0-py2.py3-none-any.whl
  python/avi/migrationtools/lib/vapi_runtime-2.29.0-py2.py3-none-any.whl
  python/avi/migrationtools/nsxt_converter/__init__.py
  python/avi/migrationtools/nsxt_converter/conversion_util.py
  python/avi/migrationtools/nsxt_converter/install_nsx_dependencies.py
  python/avi/migrationtools/nsxt_converter/nsxt_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/persistant_converter.py
  python/avi/migrationtools/nsxt_converter/policy_converter.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
  python/avi/migrationtools/setup.py
  python/avi/sdk/avi_api.py
  python/avi/sdk/samples/virtualservice_examples_api.py
  python/avi/sdk/samples/virtualservice_examples_saml_api.py
  python/avi/sdk/samples/virtualservice_examples_sdk.py
  python/version.py
Labels: AUTO PR, cla-not-required

#2420 Auto updated assets for swagger 22.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#2421 Auto updated assets for go models and clients eng
  go/models/waf_rule.go
Labels: AUTO PR, cla-not-required

#2424 Auto updated assets for docs eng
  docs/WafApplicationSignatureProvider/index.html
  docs/WafCRS/index.html
  docs/WafPolicy/index.html
Labels: AUTO PR, cla-not-required

#2425 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/WafRule.java
Labels: AUTO PR, cla-not-required

#2426 Auto updated assets for go models and clients 21.1.6
  go/models/virtual_service.go
Labels: AUTO PR, cla-not-required

#2431 Auto updated assets for docs 22.1.2
  docs/metrics_query.html
Labels: AUTO PR, cla-not-required

#2435 AV-156969: Synced migration tools code from avi-dev eng to alb-sdk 22.1.2
  python/avi/migrationtools/README.md
  python/avi/migrationtools/config_patch.py
  python/avi/migrationtools/f5_converter/command_status.yaml
  python/avi/migrationtools/f5_converter/conversion_util.py
  python/avi/migrationtools/f5_converter/f5_config_converter.py
  python/avi/migrationtools/f5_converter/profile_converter.py
  python/avi/migrationtools/f5_converter/test/hol_advanced_bigip.conf
  python/avi/migrationtools/f5_converter/test/test_migrationtool.py
  python/avi/migrationtools/f5_converter/vs_converter.py
  python/avi/migrationtools/nsxt_converter/NSX-T_to_Avi_Migration_Tool_-_How_To_Guide.pdf
  python/avi/migrationtools/nsxt_converter/README.md
  python/avi/migrationtools/nsxt_converter/persistant_converter.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/profile_converter.py
  python/avi/migrationtools/pb_attributes.yaml
Labels: cla-not-required

#2436 AV-156969: Synced migration tools code from avi-dev eng to alb-sdk eng
  python/avi/migrationtools/README.md
  python/avi/migrationtools/f5_converter/test/hol_advanced_bigip.conf
  python/avi/migrationtools/f5_converter/test/test_migrationtool.py
  python/avi/migrationtools/nsxt_converter/NSX-T_to_Avi_Migration_Tool_-_How_To_Guide.pdf
  python/avi/migrationtools/nsxt_converter/README.md
  python/avi/migrationtools/nsxt_converter/persistant_converter.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/profile_converter.py
  python/avi/migrationtools/pb_attributes.yaml
Labels: cla-not-required

#2437 AV-156969: Synced latest changes from avi-dev eng to alb-sdk eng
  python/avi/migrationtools/nsxt_converter/nsxt_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
Labels: cla-not-required

#2438 AV-156969: Synced latest changes from avi-dev eng to alb-sdk 22.1.2
  python/avi/migrationtools/nsxt_converter/nsxt_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
Labels: cla-not-required

#2439 AV-157124: Fixed issue while writing excelsheet with the latest pandas version
  python/avi/migrationtools/nsxt_converter/conversion_util.py
  python/avi/migrationtools/nsxt_converter/nsxt_config_converter.py
Labels: cla-not-required

#2440 AV-157124: Fixed issue while writing excelsheet with the latest pandas version
  python/avi/migrationtools/nsxt_converter/conversion_util.py
  python/avi/migrationtools/nsxt_converter/nsxt_config_converter.py
Labels: cla-not-required
