Repository vmware/alb-sdk, pull requests merged in 2022-11, with the labels that each got.

#2497 AV-159765: Synced changes from alb-sdk eng to alb-sdk 22.1.2
  .github/workflows/release.yml
  python/avi/migrationtools/nsxt_converter/nsxt_cleanup.py
  python/avi/migrationtools/nsxt_converter/nsxt_rollback.py
  python/avi/migrationtools/nsxt_converter/nsxt_traffic_cutover.py
  python/avi/migrationtools/nsxt_converter/persistant_converter.py
  python/avi/migrationtools/setup.py
Labels: cla-not-required

#2499 Auto updated assets for docs eng
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/GslbInventory/index.html
  docs/GslbService/index.html
  docs/GslbServiceInventory/index.html
  docs/Image/index.html
  docs/UpgradeStatusInfo/index.html
Labels: AUTO PR, cla-not-required

#2487 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/AppSignatureConfig.java
  java/src/com/vmware/avi/sdk/model/ControllerInterface.java
  java/src/com/vmware/avi/sdk/model/GslbPool.java
  java/src/com/vmware/avi/sdk/model/SpGslbServiceInfo.java
  java/src/com/vmware/avi/sdk/model/SystemConfiguration.java
Labels: AUTO PR, cla-not-required

#2502 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/EventDetails.java
  java/src/com/vmware/avi/sdk/model/VIMgrNWRuntime.java
  java/src/com/vmware/avi/sdk/model/VcenterDatastore.java
  java/src/com/vmware/avi/sdk/model/VcenterTagEventDetails.java
  java/src/com/vmware/avi/sdk/model/vCenterConfiguration.java
Labels: AUTO PR, cla-not-required

#2508 AV-103074: F5 Migration Tools Enhancements
  python/avi/migrationtools/avi_migration_utils.py
  python/avi/migrationtools/f5_converter/command_status.yaml
  python/avi/migrationtools/f5_converter/conversion_util.py
  python/avi/migrationtools/f5_converter/datagroup_converter.py
  python/avi/migrationtools/f5_converter/f5_config_converter.py
  python/avi/migrationtools/f5_converter/f5_converter.py
  python/avi/migrationtools/f5_converter/monitor_converter.py
  python/avi/migrationtools/f5_converter/persistence_converter.py
  python/avi/migrationtools/f5_converter/policy_converter.py
  python/avi/migrationtools/f5_converter/pool_converter.py
  python/avi/migrationtools/f5_converter/profile_converter.py
  python/avi/migrationtools/f5_converter/test/test_migrationtool.py
  python/avi/migrationtools/f5_converter/vs_converter.py
Labels: cla-not-required

#2506 Bump jackson-databind version from 2.12.7 to 2.12.7.1 in Java SDK.
  java/pom.xml
Labels: cla-not-required

#2505 AV-160498: Added import self signed certificate changes in Java SDK.
  java/src/com/vmware/avi/sdk/AviCredentials.java
  java/src/com/vmware/avi/sdk/AviRestUtils.java
Labels: cla-not-required

#2490 Auto updated assets for java 21.1.6
  java/src/com/vmware/avi/sdk/model/AppSignatureConfig.java
Labels: AUTO PR, cla-not-required

#2509 AV-160498: Added import self signed certificate changes in Java SDK.
  java/src/com/vmware/avi/sdk/AviCredentials.java
  java/src/com/vmware/avi/sdk/AviRestUtils.java
Labels: Cherry-pick, cla-not-required

#2476 Auto updated assets for go models and clients eng
  go/models/alert_object_list.go
  go/models/app_signature_config.go
  go/models/c_c_vnic_info.go
  go/models/controller_interface.go
  go/models/event_details.go
  go/models/event_log.go
  go/models/gslb_pool.go
  go/models/gslb_service.go
  go/models/gslb_site_runtime_stats.go
  go/models/pool.go
  go/models/s_s_l_key_and_certificate.go
  go/models/s_s_l_profile.go
  go/models/se_hm_event_gslb_pool_member_details.go
  go/models/se_hm_event_server_details.go
  go/models/server_auto_scale_failed_info.go
  go/models/server_auto_scale_in_complete_info.go
  go/models/server_auto_scale_in_info.go
  go/models/server_auto_scale_out_complete_info.go
  go/models/server_auto_scale_out_info.go
  go/models/sp_gslb_service_info.go
  go/models/system_configuration.go
  go/models/upgrade_readiness_check_obj.go
  go/models/v_center_configuration.go
  go/models/v_i_mgr_n_w_runtime.go
  go/models/vcenter_datastore.go
  go/models/vcenter_tag_event_details.go
Labels: AUTO PR, cla-not-required
