Repository vmware/alb-sdk, pull requests merged in 2022-04, with the labels that each got.

#2047 Auto updated assets for swagger 20.1.9
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#2053 Auto updated assets for swagger 21.1.4
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#2054 Auto updated assets for python 21.1.4
  python/avi/migrationtools/test/common/test_clean_reboot.py
Labels: AUTO PR, cla-not-required

#2055 Revert "Auto updated assets for python 21.1.4"
  python/avi/migrationtools/test/common/test_clean_reboot.py
Labels: cla-not-required

#2057 Auto updated assets for go models and clients eng
  go/models/event_gen_params.go
  go/models/event_log.go
Labels: AUTO PR, cla-not-required

#2059 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/VIMgrVcenterRuntime/index.html
Labels: AUTO PR, cla-not-required

#2061 Auto updated assets for python 21.1.4
  python/avi/migrationtools/test/common/test_clean_reboot.py
Labels: AUTO PR, cla-not-required

#2064 Auto updated assets for docs 20.1.9
  docs/ApplicationProfile/index.html
Labels: AUTO PR, cla-not-required

#2065 Auto updated assets for java 20.1.9
  java/src/com/vmware/avi/sdk/model/HTTPApplicationProfile.java
Labels: AUTO PR, cla-not-required

#2066 Auto updated assets for go models and clients eng
  go/models/action.go
  go/models/apply_log_recommendations.go
  go/models/get_log_recommendations.go
  go/models/http_application_profile.go
  go/models/recommendation_request.go
  go/models/waf_policy_c_r_s_update.go
Labels: AUTO PR, cla-not-required

#2068 Auto updated assets for docs eng
  docs/ApplicationProfile/index.html
  docs/VirtualService/index.html
  docs/WafPolicy/index.html
Labels: AUTO PR, cla-not-required

#2062 Auto updated assets for go models and clients 20.1.9
  go/models/http_application_profile.go
Labels: AUTO PR, cla-not-required

#2069 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/Action.java
  java/src/com/vmware/avi/sdk/model/ApplyLogRecommendations.java
  java/src/com/vmware/avi/sdk/model/GetLogRecommendations.java
  java/src/com/vmware/avi/sdk/model/HTTPApplicationProfile.java
  java/src/com/vmware/avi/sdk/model/RecommendationRequest.java
  java/src/com/vmware/avi/sdk/model/WafPolicyCRSUpdate.java
Labels: AUTO PR, cla-not-required

#2070 Auto updated assets for swagger 20.1.9
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#2087 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AuthMappingProfile/index.html
  docs/ServiceEngine/index.html
  docs/SystemConfiguration/index.html
Labels: AUTO PR, cla-not-required

#2088 Auto updated assets for java eng
  java/pom.xml
  java/src/com/vmware/avi/sdk/model/AuthMappingProfile.java
  java/src/com/vmware/avi/sdk/model/EventDetails.java
  java/src/com/vmware/avi/sdk/model/MetricsGRPCAuthFailureDetails.java
  java/src/com/vmware/avi/sdk/model/RemoteAuthConfiguration.java
Labels: AUTO PR, cla-not-required
