Repository vmware/alb-sdk, pull requests merged in 2022-03, with the labels that each got.

#1985 Auto updated assets for go models and clients eng
  go/models/central_license_refresh_details.go
  go/models/central_license_subscription_details.go
  go/models/conn_pool_properties.go
  go/models/dsr_profile.go
  go/models/event_details.go
  go/models/geo_d_b.go
  go/models/license_service_update.go
  go/models/license_status.go
  go/models/org_service_units.go
  go/models/scale_status.go
  go/models/supported_migrations.go
  go/models/user_account_profile.go
  go/models/user_activity.go
  go/models/w_a_f_limits.go
  go/models/waf_config.go
  go/session/avisession.go
Labels: AUTO PR, cla-not-required

#1993 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/AviAuthorizationInterceptor.java
  java/src/com/vmware/avi/sdk/model/ConnPoolProperties.java
  java/src/com/vmware/avi/sdk/model/SupportedMigrations.java
Labels: AUTO PR, cla-not-required

#1991 Auto updated assets for docs eng
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/Image/index.html
  docs/Pool/index.html
  docs/UserAccountProfile/index.html
  docs/UserActivity/index.html
Labels: AUTO PR, cla-not-required

#1998 Auto updated assets for go models and clients 21.1.4
  go/models/controller_properties.go
  go/models/dsr_profile.go
  go/models/geo_d_b.go
  go/models/scale_status.go
  go/models/supported_migrations.go
Labels: AUTO PR, cla-not-required

#2001 Auto updated assets for docs 21.1.4
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/CloudProperties/index.html
  docs/ControllerProperties/index.html
  docs/GeoDB/index.html
  docs/Image/index.html
  docs/NetworkProfile/index.html
  docs/VIMgrVcenterRuntime/index.html
  docs/metrics_query.html
Labels: AUTO PR, cla-not-required

#2002 Auto updated assets for java 21.1.4
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/DsrProfile.java
  java/src/com/vmware/avi/sdk/model/SupportedMigrations.java
Labels: AUTO PR, cla-not-required

#1989 Auto updated assets for swagger 20.1.9
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#2000 Auto updated assets for python 21.1.4
  python/version.py
Labels: AUTO PR, cla-not-required

#2003 Auto updated assets for swagger 20.1.9
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#2004 Auto updated assets for go models and clients eng
  go/models/b_o_t_limits.go
  go/models/controller_limits.go
Labels: AUTO PR, cla-not-required

#2006 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/SystemLimits/index.html
Labels: AUTO PR, cla-not-required

#2007 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/BOTLimits.java
  java/src/com/vmware/avi/sdk/model/ControllerLimits.java
Labels: AUTO PR, cla-not-required

#2009 Auto updated assets for swagger 20.1.9
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#2013 Auto updated assets for docs 21.1.4
  docs/SystemConfiguration/index.html
Labels: AUTO PR, cla-not-required

#2010 Auto updated assets for go models and clients 21.1.4
  go/models/email_configuration.go
Labels: AUTO PR, cla-not-required

#2014 Auto updated assets for java 21.1.4
  java/src/com/vmware/avi/sdk/model/EmailConfiguration.java
Labels: AUTO PR, cla-not-required

#2012 Auto updated assets for python 21.1.4
  python/avi/migrationtools/test/common/test_clean_reboot.py
Labels: AUTO PR, cla-not-required

#2015 Auto updated assets for swagger 20.1.9
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR

#2017 Auto updated assets for docs 21.1.4
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
Labels: AUTO PR, cla-not-required

#2018 Auto updated assets for swagger 20.1.9
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#1997 Auto updated assets for python eng
  python/avi/migrationtools/test/common/test_clean_reboot.py
Labels: AUTO PR, cla-not-required

#2024 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/ApplicationProfile/index.html
  docs/Cloud/index.html
  docs/CloudProperties/index.html
  docs/ControllerProperties/index.html
  docs/DebugVirtualService/index.html
  docs/PKIProfile/index.html
  docs/logs.html
Labels: AUTO PR, cla-not-required

#2021 Auto updated assets for go models and clients eng
  go/models/application_log.go
  go/models/client_finger_prints.go
  go/models/cloud.go
  go/models/controller_properties.go
  go/models/http_application_profile.go
  go/models/tls_client_info.go
  go/models/waf_log.go
Labels: AUTO PR, cla-not-required

#2023 Auto updated assets for python eng
  python/avi/migrationtools/nsxt_converter/__init__.py
  python/avi/migrationtools/nsxt_converter/alb_converter.py
  python/avi/migrationtools/nsxt_converter/base_client.py
  python/avi/migrationtools/nsxt_converter/command_status.yaml
  python/avi/migrationtools/nsxt_converter/conversion_util.py
  python/avi/migrationtools/nsxt_converter/converter_constants.py
  python/avi/migrationtools/nsxt_converter/custom_config.yaml
  python/avi/migrationtools/nsxt_converter/get_certificates.py
  python/avi/migrationtools/nsxt_converter/monitor_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_client.py
  python/avi/migrationtools/nsxt_converter/nsxt_config_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/patch.yaml
  python/avi/migrationtools/nsxt_converter/persistant_converter.py
  python/avi/migrationtools/nsxt_converter/policy_converter.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/profile_converter.py
  python/avi/migrationtools/nsxt_converter/ssl_profile_converter.py
  python/avi/migrationtools/nsxt_converter/test/avi_config.json
  python/avi/migrationtools/nsxt_converter/test/config.json
  python/avi/migrationtools/nsxt_converter/test/conftest.py
  python/avi/migrationtools/nsxt_converter/test/excel_reader.py
  python/avi/migrationtools/nsxt_converter/test/test_monitor_converter.conf
  python/avi/migrationtools/nsxt_converter/test/test_monitor_converter.py
  python/avi/migrationtools/nsxt_converter/test/test_nsxt_converter.py
  python/avi/migrationtools/nsxt_converter/test/test_pool_converter.conf
  python/avi/migrationtools/nsxt_converter/test/test_pool_converter.py
  python/avi/migrationtools/nsxt_converter/test/test_profile_converter.conf
  python/avi/migrationtools/nsxt_converter/test/test_profile_converter.py
  python/avi/migrationtools/nsxt_converter/test_cd.py
  python/avi/migrationtools/nsxt_converter/v_client.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
  python/avi/migrationtools/test/common/test_clean_reboot.py
Labels: AUTO PR, cla-not-required

#2027 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/ApplicationProfile/index.html
  docs/DnsPolicy/index.html
  docs/HTTPPolicySet/index.html
  docs/NetworkProfile/index.html
  docs/Pool/index.html
  docs/VSDataScriptSet/index.html
  docs/VirtualService/index.html
Labels: AUTO PR, cla-not-required

#2028 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/ApplicationLog.java
  java/src/com/vmware/avi/sdk/model/ClientFingerPrints.java
  java/src/com/vmware/avi/sdk/model/Cloud.java
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/HTTPApplicationProfile.java
  java/src/com/vmware/avi/sdk/model/NetworkProfile.java
  java/src/com/vmware/avi/sdk/model/RateLimiter.java
  java/src/com/vmware/avi/sdk/model/RateLimiterAction.java
  java/src/com/vmware/avi/sdk/model/RateProfile.java
  java/src/com/vmware/avi/sdk/model/TlsClientInfo.java
  java/src/com/vmware/avi/sdk/model/WafLog.java
Labels: AUTO PR, cla-not-required

#2025 Auto updated assets for go models and clients eng
  go/models/network_profile.go
  go/models/rate_limiter.go
  go/models/rate_limiter_action.go
  go/models/rate_profile.go
Labels: AUTO PR, cla-not-required

#2029 Auto updated assets for go models and clients 21.1.4
  go/models/network_profile.go
  go/models/rate_limiter.go
  go/models/rate_limiter_action.go
  go/models/rate_profile.go
Labels: AUTO PR, cla-not-required

#2031 Auto updated assets for docs 21.1.4
  docs/Alert/index.html
  docs/ApplicationProfile/index.html
  docs/DnsPolicy/index.html
  docs/HTTPPolicySet/index.html
  docs/NetworkProfile/index.html
  docs/Pool/index.html
  docs/VSDataScriptSet/index.html
  docs/VirtualService/index.html
Labels: AUTO PR, cla-not-required

#2032 Auto updated assets for java 21.1.4
  java/src/com/vmware/avi/sdk/model/NetworkProfile.java
  java/src/com/vmware/avi/sdk/model/RateLimiter.java
  java/src/com/vmware/avi/sdk/model/RateLimiterAction.java
  java/src/com/vmware/avi/sdk/model/RateProfile.java
Labels: AUTO PR, cla-not-required

#2034 Added changes for pom.xml
  java/pom.xml
Labels: cla-not-required

#2038 Auto updated assets for go models and clients eng
  go/models/backup_configuration.go
  go/models/gcp_info.go
  go/models/o_auth_profile.go
  go/models/sub_resource.go
Labels: AUTO PR, cla-not-required

#2040 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
  docs/AuthProfile/index.html
  docs/BackupConfiguration/index.html
  docs/Role/index.html
  docs/logs.html
Labels: AUTO PR, cla-not-required

#2041 Auto updated assets for java eng
  java/pom.xml
  java/src/com/vmware/avi/sdk/model/BackupConfiguration.java
  java/src/com/vmware/avi/sdk/model/GcpInfo.java
  java/src/com/vmware/avi/sdk/model/SubResource.java
Labels: AUTO PR, cla-not-required

#2043 Auto updated assets for docs 21.1.4
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
  docs/Image/index.html
Labels: AUTO PR, cla-not-required

#2036 AV-132375: Username password cannot be same
  python/avi/migrationtools/test/common/test_clean_reboot.py
Labels: cla-not-required
