Repository vmware/alb-sdk, pull requests merged in 2022-08, with the labels that each got.

#2294 AV-151083: Bump jackson-databind from 2.12.6 to 2.12.7 in Java SDK
  java/pom.xml
Labels: Cherry-pick

#2296 AV-151083: Bump jackson-databind from 2.12.6 to 2.12.7 in Java SDK
  java/pom.xml
Labels: Cherry-pick

#2295 AV-151083: Bump jackson-databind from 2.12.6 to 2.12.7 in Java SDK
  java/pom.xml
Labels: Cherry-pick

#2281 Auto updated assets for python 21.1.5
  python/avi/migrationtools/test/common/test_clean_reboot.py
Labels: AUTO PR, cla-not-required

#2300 Auto updated assets for docs 22.1.2
  docs/index.html
Labels: AUTO PR

#2309 Auto updated assets for java 21.1.5
  java/pom.xml
  java/src/com/vmware/avi/sdk/model/HTTPApplicationProfile.java
  java/src/com/vmware/avi/sdk/model/Pool.java
Labels: AUTO PR, cla-not-required

#2308 Auto updated assets for docs 21.1.5
  docs/ApplicationProfile/index.html
  docs/Pool/index.html
Labels: AUTO PR, cla-not-required

#2306 Auto updated assets for go models and clients 21.1.5
  go/models/http_application_profile.go
  go/models/pool.go
Labels: AUTO PR, cla-not-required

#2301 Auto updated assets for java 22.1.2
  java/pom.xml
Labels: AUTO PR, cla-not-required

#2302 Auto updated assets for go models and clients eng
  go/models/debug_service_engine.go
  go/models/http_application_profile.go
  go/models/pool.go
Labels: AUTO PR, cla-not-required

#2304 Auto updated assets for docs eng
  docs/ApplicationProfile/index.html
  docs/DebugServiceEngine/index.html
  docs/Pool/index.html
  docs/index.html
Labels: AUTO PR, cla-not-required

#2305 Auto updated assets for java eng
  java/pom.xml
  java/src/com/vmware/avi/sdk/model/DebugServiceEngine.java
  java/src/com/vmware/avi/sdk/model/HTTPApplicationProfile.java
  java/src/com/vmware/avi/sdk/model/Pool.java
Labels: AUTO PR, cla-not-required

#2318 Auto updated assets for docs 22.1.2
  docs/Cloud/index.html
  docs/Pool/index.html
Labels: AUTO PR, cla-not-required

#2316 Auto updated assets for go models and clients 22.1.2
  go/models/open_stack_configuration.go
  go/models/pool.go
Labels: AUTO PR, cla-not-required

#2319 Auto updated assets for java 22.1.2
  java/resources/config.properties
  java/src/com/vmware/avi/sdk/AviApi.java
  java/src/com/vmware/avi/sdk/model/OpenStackConfiguration.java
  java/src/com/vmware/avi/sdk/model/Pool.java
Labels: AUTO PR, cla-not-required

#2320 Auto updated assets for go models and clients eng
  go/models/c_c_vnic_info.go
  go/models/open_stack_configuration.go
  go/models/server_auto_scale_failed_info.go
  go/models/server_auto_scale_in_complete_info.go
  go/models/server_auto_scale_in_info.go
  go/models/server_auto_scale_out_complete_info.go
  go/models/server_auto_scale_out_info.go
Labels: AUTO PR, cla-not-required

#2322 Auto updated assets for docs eng
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/Cloud/index.html
  docs/GslbInventory/index.html
  docs/GslbServiceInventory/index.html
  docs/Image/index.html
Labels: AUTO PR, cla-not-required

#2328 Auto updated assets for docs 22.1.2
  docs/ServiceEngineGroup/index.html
  docs/ServiceEngineGroupInventory/index.html
Labels: AUTO PR, cla-not-required

#2329 Auto updated assets for java 22.1.2
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
Labels: AUTO PR, cla-not-required

#2284 Auto updated assets for python 22.1.2
  python/avi/migrationtools/avi_converter.py
  python/avi/migrationtools/avi_migration_utils.py
  python/avi/migrationtools/f5_converter/f5_converter.py
  python/avi/migrationtools/nsxt_converter/__init__.py
  python/avi/migrationtools/nsxt_converter/alb_converter.py
  python/avi/migrationtools/nsxt_converter/base_client.py
  python/avi/migrationtools/nsxt_converter/cleanup.py
  python/avi/migrationtools/nsxt_converter/command_status.yaml
  python/avi/migrationtools/nsxt_converter/conversion_util.py
  python/avi/migrationtools/nsxt_converter/get_certificates.py
  python/avi/migrationtools/nsxt_converter/monitor_converter.py
  python/avi/migrationtools/nsxt_converter/nsx_cleanup.py
  python/avi/migrationtools/nsxt_converter/nsxt_client.py
  python/avi/migrationtools/nsxt_converter/nsxt_config_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/persistant_converter.py
  python/avi/migrationtools/nsxt_converter/policy_converter.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/profile_converter.py
  python/avi/migrationtools/nsxt_converter/rollback.py
  python/avi/migrationtools/nsxt_converter/ssl_profile_converter.py
  python/avi/migrationtools/nsxt_converter/test/__init__.py
  python/avi/migrationtools/nsxt_converter/test/config.yaml
  python/avi/migrationtools/nsxt_converter/test/conftest.py
  python/avi/migrationtools/nsxt_converter/test/default_params.json
  python/avi/migrationtools/nsxt_converter/test/patch.yaml
  python/avi/migrationtools/nsxt_converter/test/test_migrationtool.py
  python/avi/migrationtools/nsxt_converter/test/test_nsxt_functional.py
  python/avi/migrationtools/nsxt_converter/test/utils/ansible.yml
  python/avi/migrationtools/nsxt_converter/test/utils/constants.py
  python/avi/migrationtools/nsxt_converter/test/utils/inventory
  python/avi/migrationtools/nsxt_converter/test/utils/utils.py
  python/avi/migrationtools/nsxt_converter/traffic_cutover.py
  python/avi/migrationtools/nsxt_converter/v_client.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
  python/avi/migrationtools/setup.py
  python/avi/migrationtools/test/common/excel_reader.py
  python/avi/migrationtools/test/common/test_clean_reboot.py
  python/avi/migrationtools/vs_filter.py
Labels: AUTO PR, cla-not-required

#2330 Auto updated assets for swagger 22.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required

#2326 Auto updated assets for go models and clients 22.1.2
  go/models/service_engine_group.go
Labels: AUTO PR, cla-not-required

#2213 Auto updated assets for python eng
  python/avi/migrationtools/avi_migration_utils.py
  python/avi/migrationtools/avi_orphan_object.py
  python/avi/migrationtools/config_patch.py
  python/avi/migrationtools/f5_converter/command_status.yaml
  python/avi/migrationtools/f5_converter/conversion_util.py
  python/avi/migrationtools/f5_converter/f5_converter.py
  python/avi/migrationtools/f5_converter/monitor_converter.py
  python/avi/migrationtools/f5_converter/test/patch.yaml
  python/avi/migrationtools/lib/__init__.py
  python/avi/migrationtools/lib/nsx_policy_python_sdk-4.0.0.1.0-py2.py3-none-any.whl
  python/avi/migrationtools/lib/nsx_python_sdk-4.0.0.1.0-py2.py3-none-any.whl
  python/avi/migrationtools/lib/vapi_common_client-2.29.0-py2.py3-none-any.whl
  python/avi/migrationtools/lib/vapi_runtime-2.29.0-py2.py3-none-any.whl
  python/avi/migrationtools/nsxt_converter/__init__.py
  python/avi/migrationtools/nsxt_converter/alb_converter.py
  python/avi/migrationtools/nsxt_converter/base_client.py
  python/avi/migrationtools/nsxt_converter/cleanup.py
  python/avi/migrationtools/nsxt_converter/command_status.yaml
  python/avi/migrationtools/nsxt_converter/conversion_util.py
  python/avi/migrationtools/nsxt_converter/get_certificates.py
  python/avi/migrationtools/nsxt_converter/monitor_converter.py
  python/avi/migrationtools/nsxt_converter/nsx_cleanup.py
  python/avi/migrationtools/nsxt_converter/nsxt_client.py
  python/avi/migrationtools/nsxt_converter/nsxt_config_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/persistant_converter.py
  python/avi/migrationtools/nsxt_converter/policy_converter.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/profile_converter.py
  python/avi/migrationtools/nsxt_converter/rollback.py
  python/avi/migrationtools/nsxt_converter/ssl_profile_converter.py
  python/avi/migrationtools/nsxt_converter/test/__init__.py
  python/avi/migrationtools/nsxt_converter/test/config.yaml
  python/avi/migrationtools/nsxt_converter/test/conftest.py
  python/avi/migrationtools/nsxt_converter/test/default_params.json
  python/avi/migrationtools/nsxt_converter/test/patch.yaml
  python/avi/migrationtools/nsxt_converter/test/test_migrationtool.py
  python/avi/migrationtools/nsxt_converter/test/test_nsxt_functional.py
  python/avi/migrationtools/nsxt_converter/test/utils/ansible.yml
  python/avi/migrationtools/nsxt_converter/test/utils/constants.py
  python/avi/migrationtools/nsxt_converter/test/utils/inventory
  python/avi/migrationtools/nsxt_converter/test/utils/utils.py
  python/avi/migrationtools/nsxt_converter/traffic_cutover.py
  python/avi/migrationtools/nsxt_converter/v_client.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
  python/avi/migrationtools/setup.py
  python/avi/migrationtools/test/common/excel_reader.py
  python/avi/migrationtools/test/common/test_clean_reboot.py
  python/avi/sdk/samples/custom_dns_script_infoblox.py
Labels: AUTO PR, cla-not-required

#2323 Auto updated assets for java eng
  java/resources/config.properties
  java/src/com/vmware/avi/sdk/AviApi.java
  java/src/com/vmware/avi/sdk/model/OpenStackConfiguration.java
Labels: AUTO PR, cla-not-required

#2334 Auto updated assets for go models and clients 22.1.2
  go/models/admin_auth_configuration.go
Labels: AUTO PR, cla-not-required

#2338 AV-153408: Added changes in github action for Java SDK jar release.
  .github/workflows/release.yml
Labels: cla-not-required

#2342 Auto updated assets for swagger 22.1.2
  swagger/Alert.json
  swagger/Alert.yaml
Labels: AUTO PR, cla-not-required
