Repository vmware/alb-sdk, pull requests merged in 2023-08, with the labels that each got.

#2726 Auto updated assets for python eng
  python/avi/migrationtools/pb_attributes.yaml
  python/version.py
Labels: AUTO PR, cla-not-required

#2733 Auto updated assets for java 22.1.5
  java/README.md
  java/pom.xml
  java/src/com/vmware/avi/sdk/AviApi.java
  java/src/com/vmware/avi/sdk/AviRestUtils.java
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/Gslb.java
  java/src/com/vmware/avi/sdk/model/GslbPoolMemberRuntimeInfo.java
  java/src/com/vmware/avi/sdk/model/GslbSiteRuntime.java
  java/src/com/vmware/avi/sdk/model/GslbThirdPartySiteRuntime.java
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
  java/test/com/vmware/avi/sdk/AviSDKTest.java
Labels: AUTO PR, cla-not-required

#2731 Auto updated assets for python 22.1.5
  python/avi/migrationtools/nsxt_converter/command_status.yaml
  python/avi/migrationtools/nsxt_converter/nsxt_config_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/persistant_converter.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
  python/avi/migrationtools/pb_attributes.yaml
  python/avi/sdk/test/test_avi_api.py
  python/version.py
Labels: AUTO PR, cla-not-required

#2729 Auto updated assets for go models and clients 22.1.5
  go/models/gslb.go
  go/models/gslb_pool_member_runtime_info.go
  go/models/gslb_site_runtime.go
  go/models/gslb_third_party_site_runtime.go
Labels: AUTO PR, cla-not-required

#2728 Auto updated assets for java eng
  java/src/com/vmware/avi/sdk/model/AdminAuthConfiguration.java
  java/src/com/vmware/avi/sdk/model/GslbPoolMemberRuntimeInfo.java
  java/src/com/vmware/avi/sdk/model/GslbServiceDownResponse.java
  java/src/com/vmware/avi/sdk/model/GslbSiteRuntime.java
  java/src/com/vmware/avi/sdk/model/GslbThirdPartySiteRuntime.java
  java/src/com/vmware/avi/sdk/model/ServiceAuthConfiguration.java
  java/src/com/vmware/avi/sdk/model/ServiceAuthProfile.java
  java/src/com/vmware/avi/sdk/model/ServiceAuthProfileApiResponse.java
  java/src/com/vmware/avi/sdk/model/ServiceOAuth.java
Labels: AUTO PR, cla-not-required

#2724 Auto updated assets for go models and clients eng
  go/clients/avi_client.go
  go/clients/serviceauthprofile_client.go
  go/models/admin_auth_configuration.go
  go/models/alert_object_list.go
  go/models/build_info.go
  go/models/c_c_vnic_info.go
  go/models/controller_portal_auth.go
  go/models/controller_properties.go
  go/models/event_log.go
  go/models/gslb_pool_member_runtime_info.go
  go/models/gslb_service_down_response.go
  go/models/gslb_site_runtime.go
  go/models/gslb_third_party_site_runtime.go
  go/models/image.go
  go/models/permission.go
  go/models/server_auto_scale_failed_info.go
  go/models/server_auto_scale_in_complete_info.go
  go/models/server_auto_scale_in_info.go
  go/models/server_auto_scale_out_complete_info.go
  go/models/server_auto_scale_out_info.go
  go/models/service_auth_configuration.go
  go/models/service_auth_profile.go
  go/models/service_auth_profile_api_response.go
  go/models/service_o_auth.go
  go/models/sub_job.go
  go/models/upgrade_status_info.go
  go/models/user.go
Labels: AUTO PR, cla-not-required

#2708 Auto updated assets for python 30.1.1
  python/avi/migrationtools/ansible/ansible_config_converter.py
  python/avi/sdk/saml_avi_api.py
  python/avi/sdk/test/test_avi_api.py
  python/version.py
Labels: AUTO PR, cla-not-required

#2710 Auto updated assets for java 30.1.1
  java/README.md
  java/pom.xml
  java/src/com/vmware/avi/sdk/AviApi.java
  java/src/com/vmware/avi/sdk/AviRestUtils.java
  java/src/com/vmware/avi/sdk/model/BackupConfiguration.java
  java/src/com/vmware/avi/sdk/model/ControllerPortalAuth.java
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/Gslb.java
  java/src/com/vmware/avi/sdk/model/Image.java
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
  java/src/com/vmware/avi/sdk/model/UpgradeStatusInfo.java
  java/test/com/vmware/avi/sdk/AviSDKTest.java
Labels: AUTO PR, cla-not-required

#2723 Auto updated assets for go models and clients 30.1.1
  go/models/c_c_vnic_info.go
  go/models/controller_portal_auth.go
  go/models/server_auto_scale_failed_info.go
  go/models/server_auto_scale_in_complete_info.go
  go/models/server_auto_scale_in_info.go
  go/models/server_auto_scale_out_complete_info.go
  go/models/server_auto_scale_out_info.go
Labels: AUTO PR, cla-not-required

#2746 Fixed the error check and return new error if its not there.
  go/session/avisession.go
Labels: cla-not-required

#2747 Fixed the error check and return new error if its not there
  go/session/avisession.go
Labels: Cherry-pick, cla-not-required

#2748 Fixed the error check and return new error if its not there
  go/session/avisession.go
Labels: Cherry-pick, cla-not-required

#2736 Auto updated assets for go models and clients 30.1.1
  go/clients/avi_client.go
  go/clients/serviceauthprofile_client.go
  go/models/admin_auth_configuration.go
  go/models/alert_object_list.go
  go/models/c_c_agent_properties.go
  go/models/cloud.go
  go/models/connection_log.go
  go/models/controller_properties.go
  go/models/dns_service_application_profile.go
  go/models/event_details.go
  go/models/event_log.go
  go/models/file_reference_mapping.go
  go/models/gslb_pool_member_runtime_info.go
  go/models/gslb_site_runtime.go
  go/models/gslb_third_party_site_runtime.go
  go/models/log_agent_event_detail.go
  go/models/log_agent_tcp_conn_est_rate_excd_event.go
  go/models/nsxt_configuration.go
  go/models/permission.go
  go/models/s_a_m_l_s_p_config.go
  go/models/se_hm_event_gslb_pool_member_details.go
  go/models/se_hm_event_server_details.go
  go/models/service_auth_configuration.go
  go/models/service_auth_profile.go
  go/models/service_auth_profile_api_response.go
  go/models/service_engine_group.go
  go/models/service_o_auth.go
  go/models/tenant.go
  go/models/tenant_system_configuration.go
  go/models/user.go
  go/models/v_center_configuration.go
  go/models/vcenter_image_details.go
  go/models/vcenter_quarantined_host_params.go
Labels: AUTO PR, cla-not-required

#2738 Auto updated assets for python 30.1.1
  python/avi/migrationtools/f5_converter/conversion_util.py
  python/avi/migrationtools/f5_converter/pool_converter.py
  python/avi/migrationtools/pb_attributes.yaml
Labels: AUTO PR, cla-not-required

#2749 AV-187450: Added pagination fixes in Java SDK model.
  java/src/com/vmware/avi/sdk/model/AviApiResponse.java
Labels: cla-not-required

#2757 AV-101254 Added Re IP Support
  python/avi/migrationtools/avi_converter.py
  python/avi/migrationtools/f5_converter/f5_converter.py
  python/avi/migrationtools/f5_converter/test/test_migrationtool.py
  python/avi/migrationtools/f5_converter/test/vs_mapping.xlsx
Labels: cla-not-required

#2760 Syncing changes from eng to 30.1.1
  python/avi/migrationtools/ansible/ansible_constant.py
  python/avi/migrationtools/avi_converter.py
  python/avi/migrationtools/avi_orphan_object.py
  python/avi/migrationtools/f5_converter/f5_config_parser.py
  python/avi/migrationtools/f5_converter/f5_converter.py
  python/avi/migrationtools/f5_converter/pool_converter.py
  python/avi/migrationtools/nsxt_converter/conversion_util.py
  python/avi/migrationtools/nsxt_converter/nsxt_config_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/persistant_converter.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/ssl_profile_converter.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
  python/avi/migrationtools/pb_attributes.yaml
Labels: cla-not-required
