Repository vmware/alb-sdk, pull requests merged in 2023-11, with the labels that each got.

#2792 Auto updated assets for python eng
  python/avi/sdk/avi_api.py
Labels: AUTO PR, cla-not-required

#2793 Updated assets for python (#2792)
  python/avi/sdk/avi_api.py
Labels: cla-not-required

#2796 Revert "Updated assets for python (#2792)"
  python/avi/sdk/avi_api.py
Labels: cla-not-required

#2795 AV-192855: Error handling of cutover and rollback scripts in v2alb converter
  python/avi/migrationtools/nsxt_converter/nsxt_traffic_cutover.py
  python/avi/migrationtools/v2alb_converter/config_collector/v_config_collector.py
  python/avi/migrationtools/v2alb_converter/v2avi_utils.py
  python/avi/migrationtools/v2alb_converter/vs_converter.py
Labels: cla-not-required

#2794 Auto updated assets for python eng
  python/avi/migrationtools/avi_converter.py
  python/avi/migrationtools/f5_converter/command_status.yaml
  python/avi/migrationtools/f5_converter/conversion_util.py
  python/avi/migrationtools/f5_converter/datagroup_converter.py
  python/avi/migrationtools/f5_converter/f5_config_converter.py
  python/avi/migrationtools/f5_converter/f5_converter.py
  python/avi/migrationtools/f5_converter/irule-parser/.gitignore
  python/avi/migrationtools/f5_converter/irule-parser/__init__.py
  python/avi/migrationtools/f5_converter/irule-parser/irule_parser.py
  python/avi/migrationtools/f5_converter/irule-parser/irules/bigip.conf
  python/avi/migrationtools/f5_converter/irule-parser/requirements.txt
  python/avi/migrationtools/f5_converter/irule-parser/templates/redirect.yml
  python/avi/migrationtools/f5_converter/irule-parser/templates/redirect_rule.yml
  python/avi/migrationtools/f5_converter/irule-parser/templates/switch.yml
  python/avi/migrationtools/f5_converter/irule-parser/templates/switch_rule.yml
  python/avi/migrationtools/f5_converter/irule-parser/tests/test_data.json
  python/avi/migrationtools/f5_converter/irule-parser/tests/test_irule_parser.py
  python/avi/migrationtools/f5_converter/monitor_converter.py
  python/avi/migrationtools/f5_converter/persistence_converter.py
  python/avi/migrationtools/f5_converter/policy_converter.py
  python/avi/migrationtools/f5_converter/pool_converter.py
  python/avi/migrationtools/f5_converter/profile_converter.py
  python/avi/migrationtools/f5_converter/vs_converter.py
  python/avi/sdk/test/test_avi_api.py
Labels: AUTO PR, cla-not-required

#2785 Auto updated assets for go models and clients eng
  go/models/a_l_b_services_config.go
  go/models/alert_object_list.go
  go/models/anomaly_event_details.go
  go/models/c_s_r_f_rule.go
  go/models/controller_cloud_limits.go
  go/models/dns_service_application_profile.go
  go/models/event_log.go
  go/models/metrics_derivation_data.go
  go/models/metrics_event_threshold.go
  go/models/nsxt_configuration.go
  go/models/nsxt_tier1_segment_manual_mode.go
  go/models/pulse_services_session_config.go
  go/models/pulse_services_tenant_config.go
  go/models/s_s_l_certificate.go
  go/models/se_hm_event_gslb_pool_member_details.go
  go/models/se_hm_event_server_details.go
  go/models/session_headers.go
  go/models/v_center_configuration.go
Labels: AUTO PR, cla-not-required

#2779 Auto updated assets for docs eng
  docs/ALBServicesConfig/index.html
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
  docs/ApplicationProfile/index.html
  docs/CSRFPolicy/index.html
  docs/Cloud/index.html
  docs/CloudInventory/index.html
  docs/PKIProfile/index.html
  docs/SSLKeyAndCertificate/index.html
  docs/ServiceEngineGroup/index.html
  docs/ServiceEngineGroupInventory/index.html
  docs/SystemConfiguration/index.html
  docs/SystemLimits/index.html
  docs/VirtualService/index.html
  docs/WafProfile/index.html
  docs/anomaly/index.html
  docs/metrics/index.html
  docs/metrics_query.html
Labels: AUTO PR, cla-not-required

#2806 Auto updated assets for java 22.1.6
  java/src/com/vmware/avi/sdk/model/AlertScriptConfig.java
  java/src/com/vmware/avi/sdk/model/RoutingService.java
Labels: AUTO PR, cla-not-required

#2804 Auto updated assets for python 22.1.6
  python/version.py
Labels: AUTO PR, cla-not-required

#2802 Auto updated assets for go models and clients 22.1.6
  go/models/alert_script_config.go
  go/models/anomaly_event_details.go
  go/models/metrics_derivation_data.go
  go/models/routing_service.go
Labels: AUTO PR, cla-not-required

#2798 Auto updated assets for go models and clients eng
  go/models/alert_script_config.go
  go/models/cloud.go
  go/models/cluster_node.go
  go/models/controller_interface.go
  go/models/event_details.go
  go/models/event_log.go
  go/models/false_positive_details.go
  go/models/icap_profile.go
  go/models/ip_a_m_dns_infoblox_profile.go
  go/models/o_auth_profile.go
  go/models/pulse_services_tenant_config.go
  go/models/routing_service.go
  go/models/saml_identity_provider_settings.go
  go/models/saml_metadata_update_failed_details.go
  go/models/se_list.go
  go/models/sec_mgr_data_event.go
  go/models/sub_job.go
  go/models/system_configuration.go
  go/models/webapp_u_t.go
Labels: AUTO PR, cla-not-required

#2799 Auto updated assets for python eng
  python/avi/migrationtools/ansible/avi_config_to_ansible.py
  python/avi/migrationtools/avi_migration_utils.py
  python/avi/migrationtools/f5_converter/command_status.yaml
  python/avi/migrationtools/f5_converter/conversion_util.py
  python/avi/migrationtools/f5_converter/f5_config_converter.py
  python/avi/migrationtools/f5_converter/f5_config_parser.py
  python/avi/migrationtools/f5_converter/f5_converter.py
  python/avi/migrationtools/f5_converter/irule-parser/irules/bigip.conf
  python/avi/migrationtools/f5_converter/irule-parser/tests/test_generation_data.json
  python/avi/migrationtools/f5_converter/irule-parser/tests/test_irule_parser.py
  python/avi/migrationtools/f5_converter/irule_parser/.gitignore
  python/avi/migrationtools/f5_converter/irule_parser/__init__.py
  python/avi/migrationtools/f5_converter/irule_parser/extract_irule.py
  python/avi/migrationtools/f5_converter/irule_parser/irule_parser.py
  python/avi/migrationtools/f5_converter/irule_parser/irules/bigip.conf
  python/avi/migrationtools/f5_converter/irule_parser/requirements.txt
  python/avi/migrationtools/f5_converter/irule_parser/templates/header_op.yml
  python/avi/migrationtools/f5_converter/irule_parser/templates/header_update.yml
  python/avi/migrationtools/f5_converter/irule_parser/templates/redirect.yml
  python/avi/migrationtools/f5_converter/irule_parser/templates/redirect_rule.yml
  python/avi/migrationtools/f5_converter/irule_parser/templates/switch.yml
  python/avi/migrationtools/f5_converter/irule_parser/templates/switch_rule.yml
  python/avi/migrationtools/f5_converter/irule_parser/tests/f5_data.conf
  python/avi/migrationtools/f5_converter/irule_parser/tests/test_data.json
  python/avi/migrationtools/f5_converter/irule_parser/tests/test_generation_data.json
  python/avi/migrationtools/f5_converter/irule_parser/tests/test_irule_parser.py
  python/avi/migrationtools/f5_converter/policy_converter.py
  python/avi/migrationtools/f5_converter/vs_converter.py
  python/avi/migrationtools/nsxt_converter/monitor_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_traffic_cutover.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/policy_converter.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
  python/avi/migrationtools/v2alb_converter/config_collector/v_config_collector.py
  python/avi/migrationtools/v2alb_converter/v2avi_utils.py
  python/avi/migrationtools/v2alb_converter/vs_converter.py
  python/avi/sdk/avi_api.py
Labels: AUTO PR, cla-not-required

#2800 Auto updated assets for docs eng
  docs/ALBServicesConfig/index.html
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertScriptConfig/index.html
  docs/AuthProfile/index.html
  docs/Cloud/index.html
  docs/IcapProfile/index.html
  docs/IpamDnsProviderProfile/index.html
  docs/JobEntry/index.html
  docs/NetworkService/index.html
  docs/SystemConfiguration/index.html
  docs/WebappUT/index.html
Labels: AUTO PR, cla-not-required

#2817 Auto updated assets for docs eng
  docs/Alert/index.html
  docs/AlertConfig/index.html
Labels: AUTO PR, cla-not-required

#2814 Auto updated assets for go models and clients eng
  go/models/event_details.go
  go/models/event_log.go
  go/models/metrics_db_runtime.go
  go/models/p_k_iprofile_details.go
  go/models/se_hm_event_gslb_pool_member_details.go
  go/models/se_hm_event_server_details.go
Labels: AUTO PR
