Repository vmware/alb-sdk, pull requests merged in 2023-06, with the labels that each got.

#2670 Auto updated assets for go models and clients eng
  go/clients/avi_client.go
  go/clients/csrfpolicy_client.go
  go/examples/create_vs.go
  go/models/a_l_b_services_case.go
  go/models/a_l_b_services_config.go
  go/models/alert_object_list.go
  go/models/c_c_vnic_info.go
  go/models/c_s_r_f_policy.go
  go/models/c_s_r_f_policy_api_response.go
  go/models/c_s_r_f_rule.go
  go/models/central_license_refresh_details.go
  go/models/controller_portal_auth.go
  go/models/controller_properties.go
  go/models/event_log.go
  go/models/httpswitching_action.go
  go/models/license_status.go
  go/models/metric_thresold_up_details.go
  go/models/permission.go
  go/models/portal_feature_opt_in.go
  go/models/saml_identity_provider_settings.go
  go/models/server_auto_scale_failed_info.go
  go/models/server_auto_scale_in_complete_info.go
  go/models/server_auto_scale_in_info.go
  go/models/server_auto_scale_out_complete_info.go
  go/models/server_auto_scale_out_info.go
  go/models/virtual_service.go
  go/session/avisession.go
Labels: AUTO PR, cla-not-required

#2669 Auto updated assets for java 22.1.4
  java/pom.xml
  java/src/com/vmware/avi/sdk/AviRestUtils.java
  java/src/com/vmware/avi/sdk/model/ConnectionLog.java
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/DnsServiceApplicationProfile.java
  java/src/com/vmware/avi/sdk/model/GslbService.java
  java/src/com/vmware/avi/sdk/model/IpamDnsInfobloxProfile.java
  java/src/com/vmware/avi/sdk/model/NsxtTier1SegmentManualMode.java
  java/src/com/vmware/avi/sdk/model/vCenterConfiguration.java
Labels: AUTO PR, cla-not-required

#2668 Auto updated assets for docs 22.1.4
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
  docs/ApplicationProfile/index.html
  docs/Cloud/index.html
  docs/CloudInventory/index.html
  docs/CloudProperties/index.html
  docs/ControllerProperties/index.html
  docs/logs.html
Labels: AUTO PR, cla-not-required

#2667 Auto updated assets for python 22.1.4
  python/avi/migrationtools/f5_converter/ciphers_converter.py
  python/avi/migrationtools/f5_converter/conversion_util.py
  python/avi/migrationtools/f5_converter/f5_config_converter.py
  python/avi/migrationtools/f5_converter/f5_converter.py
  python/avi/migrationtools/f5_converter/monitor_converter.py
  python/avi/migrationtools/f5_converter/profile_converter.py
  python/avi/migrationtools/f5_converter/scp_util.py
  python/avi/migrationtools/f5_converter/test/hol_advanced_bigip.conf
  python/avi/migrationtools/f5_converter/test/test_migrationtool.py
  python/avi/migrationtools/f5_converter/vs_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_cleanup.py
  python/avi/migrationtools/nsxt_converter/nsxt_rollback.py
  python/avi/migrationtools/nsxt_converter/nsxt_traffic_cutover.py
  python/avi/migrationtools/setup.py
  python/avi/sdk/README.md
  python/avi/sdk/avi_api.py
  python/avi/sdk/saml_avi_api.py
  python/avi/sdk/samples/clone_vs.md
  python/avi/sdk/samples/clone_vs.py
  python/avi/sdk/setup.py
  python/avi/sdk/test/test_saml_api.cfg
  python/avi/sdk/test/test_saml_api.py
  python/version.py
Labels: AUTO PR, cla-not-required

#2665 Auto updated assets for go models and clients 22.1.4
  go/examples/create_vs.go
  go/models/alert_object_list.go
  go/models/connection_log.go
  go/models/controller_properties.go
  go/models/dns_service_application_profile.go
  go/models/event_log.go
  go/models/ip_a_m_dns_infoblox_profile.go
  go/models/v_center_configuration.go
  go/session/avisession.go
Labels: AUTO PR, cla-not-required

#2658 Auto updated assets for docs eng
  docs/ALBServicesConfig/index.html
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
  docs/AuthProfile/index.html
  docs/CSRFPolicy/index.html
  docs/CloudProperties/index.html
  docs/ControllerPortalRegistration/index.html
  docs/ControllerProperties/index.html
  docs/GslbInventory/index.html
  docs/GslbServiceInventory/index.html
  docs/HTTPPolicySet/index.html
  docs/Image/index.html
  docs/LicenseStatus/index.html
  docs/Role/index.html
  docs/UpgradeStatusInfo/index.html
  docs/VirtualService/index.html
  docs/index.html
Labels: cla-not-required

#2646 Auto updated assets for java 30.1.1
  java/src/com/vmware/avi/sdk/model/ALBServicesCase.java
  java/src/com/vmware/avi/sdk/model/ALBServicesConfig.java
  java/src/com/vmware/avi/sdk/model/ALBServicesFileUpload.java
  java/src/com/vmware/avi/sdk/model/ALBServicesJob.java
  java/src/com/vmware/avi/sdk/model/AlertSyslogServer.java
  java/src/com/vmware/avi/sdk/model/AuthMappingRule.java
  java/src/com/vmware/avi/sdk/model/CentralLicenseRefreshDetails.java
  java/src/com/vmware/avi/sdk/model/ConnectionLog.java
  java/src/com/vmware/avi/sdk/model/ControllerLicense.java
  java/src/com/vmware/avi/sdk/model/ControllerPortalAuth.java
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/DNSRegisterInfo.java
  java/src/com/vmware/avi/sdk/model/DnsServiceApplicationProfile.java
  java/src/com/vmware/avi/sdk/model/EmailConfiguration.java
  java/src/com/vmware/avi/sdk/model/GslbService.java
  java/src/com/vmware/avi/sdk/model/InventoryConfig.java
  java/src/com/vmware/avi/sdk/model/IpamDnsInfobloxProfile.java
  java/src/com/vmware/avi/sdk/model/LdapAuthSettings.java
  java/src/com/vmware/avi/sdk/model/LicenseStatus.java
  java/src/com/vmware/avi/sdk/model/NsxtConfiguration.java
  java/src/com/vmware/avi/sdk/model/NsxtTier1SegmentManualMode.java
  java/src/com/vmware/avi/sdk/model/OAuthProfile.java
  java/src/com/vmware/avi/sdk/model/PKIProfile.java
  java/src/com/vmware/avi/sdk/model/PortalFeatureOptIn.java
  java/src/com/vmware/avi/sdk/model/SingleLicense.java
  java/src/com/vmware/avi/sdk/model/vCenterConfiguration.java
Labels: AUTO PR, cla-not-required

#2674 Added actual error string in the new returned error
  go/session/avisession.go
Labels: cla-not-required

#2678 Added actual error string in the new returned error
  go/session/avisession.go
Labels: cla-not-required

#2675 Added actual error string in the new returned error
  go/session/avisession.go
Labels: Cherry-pick, cla-not-required

#2679 AV-180712: Added changes in Java SDK for release 22.1.4.
  java/pom.xml
  java/src/com/vmware/avi/sdk/AviApi.java
  java/src/com/vmware/avi/sdk/AviRestUtils.java
  java/test/com/vmware/avi/sdk/AviSDKTest.java
Labels: cla-not-required

#2680 Fixed Go controller, Terraform, GO SDK failure
  go/session/avisession.go
Labels: cla-not-required

#2682 AV-181382: Fixed sdk build error
  go/session/avisession.go
Labels: cla-not-required

#2681 AV-181382: Fixed the sdk build error
  go/session/avisession.go
Labels: cla-not-required

#2677 Auto updated assets for docs eng
  docs/ALBServicesConfig/index.html
  docs/Alert/index.html
  docs/AuthProfile/index.html
  docs/CloudProperties/index.html
  docs/ControllerProperties/index.html
  docs/PoolGroup/index.html
  docs/ServiceEngineGroup/index.html
  docs/ServiceEngineGroupInventory/index.html
Labels: AUTO PR, cla-not-required

#2686 AV-180818 Fixed F5 vip issue
  python/avi/migrationtools/ansible/ansible_config_converter.py
Labels: cla-not-required

#2691 Auto updated assets for docs 22.1.4
  docs/ServiceEngineGroup/index.html
  docs/ServiceEngineGroupInventory/index.html
Labels: AUTO PR, cla-not-required

#2690 Auto updated assets for python 22.1.4
  python/avi/migrationtools/ansible/ansible_config_converter.py
  python/avi/migrationtools/f5_converter/conversion_util.py
Labels: AUTO PR, cla-not-required

#2688 Auto updated assets for go models and clients 22.1.4
  go/models/service_engine_group.go
Labels: AUTO PR, cla-not-required

#2687 AV-181854: Updated file upload function description and example.
  java/README.md
  java/src/com/vmware/avi/sdk/AviApi.java
Labels: cla-not-required

#2696 AV-179362: Added fixes for spring-web CVE.
  java/pom.xml
Labels: cla-not-required

#2698 Auto updated assets for java 22.1.4
  java/README.md
  java/pom.xml
  java/src/com/vmware/avi/sdk/AviApi.java
  java/src/com/vmware/avi/sdk/AviRestUtils.java
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
  java/test/com/vmware/avi/sdk/AviSDKTest.java
Labels: AUTO PR, cla-not-required

#2699 Revert "Auto updated assets for java 22.1.4"
  java/README.md
  java/pom.xml
  java/src/com/vmware/avi/sdk/AviApi.java
  java/src/com/vmware/avi/sdk/AviRestUtils.java
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
  java/test/com/vmware/avi/sdk/AviSDKTest.java
Labels: cla-not-required

#2695 Fixed AV-182133 Python sdk clone_vs test case failure
  python/avi/sdk/test/test_avi_api.py
Labels: cla-not-required

#2704 Auto updated assets for java 30.1.1
  java/pom.xml
  java/src/com/vmware/avi/sdk/model/ALBServicesConfig.java
  java/src/com/vmware/avi/sdk/model/CentralLicenseSubscriptionDetails.java
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/MetricThresoldUpDetails.java
  java/src/com/vmware/avi/sdk/model/SamlIdentityProviderSettings.java
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
Labels: AUTO PR, cla-not-required

#2703 Auto updated assets for docs 30.1.1
  docs/ALBServicesConfig/index.html
  docs/Alert/index.html
  docs/AuthProfile/index.html
  docs/CloudProperties/index.html
  docs/ControllerProperties/index.html
  docs/ServiceEngineGroup/index.html
  docs/ServiceEngineGroupInventory/index.html
Labels: AUTO PR, cla-not-required

#2700 Auto updated assets for go models and clients 30.1.1
  go/examples/create_vs.go
  go/models/a_l_b_services_config.go
  go/models/central_license_subscription_details.go
  go/models/controller_properties.go
  go/models/metric_thresold_up_details.go
  go/models/o_auth_profile.go
  go/models/saml_identity_provider_settings.go
  go/models/service_engine_group.go
  go/session/avisession.go
Labels: AUTO PR, cla-not-required

#2705 Added fixes for network service, vs and persistent converter for NSX-T converter
  python/avi/migrationtools/nsxt_converter/nsxt_config_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/persistant_converter.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
Labels: cla-not-required

#2711 Fixes for pool and vs converter
  python/avi/migrationtools/nsxt_converter/command_status.yaml
  python/avi/migrationtools/nsxt_converter/nsxt_config_converter.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
Labels: cla-not-required

#2712 Updated the runner version
  .github/workflows/release.yml
Labels: cla-not-required

#2713 Update release.yml
  .github/workflows/release.yml
Labels: cla-not-required

#2714 Update runner
  python/version.py
Labels: cla-not-required

#2715 Update release.yml to fix the JAVA SDK package upload.
  .github/workflows/release.yml
Labels: cla-not-required
