Repository vmware/alb-sdk, pull requests merged in 2024-03, with the labels that each got.

#2896 Auto updated assets for java 22.1.6
  java/src/com/vmware/avi/sdk/model/AsyncPatchState.java
  java/src/com/vmware/avi/sdk/model/AviApiResponse.java
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/EventDetails.java
  java/src/com/vmware/avi/sdk/model/MetricsDbDiskEventDetails.java
  java/src/com/vmware/avi/sdk/model/MustChecksInfo.java
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
  java/src/com/vmware/avi/sdk/model/SystemReport.java
Labels: AUTO PR, cla-not-required

#2895 Auto updated assets for docs 22.1.6
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/CloudProperties/index.html
  docs/ControllerProperties/index.html
  docs/GslbInventory/index.html
  docs/GslbServiceInventory/index.html
  docs/Image/index.html
  docs/JobEntry/index.html
  docs/ServiceEngineGroup/index.html
  docs/ServiceEngineGroupInventory/index.html
  docs/SystemReport/index.html
  docs/UpgradeStatusInfo/index.html
Labels: AUTO PR, cla-not-required

#2889 Auto updated assets for go models and clients 22.1.6
  go/models/async_patch_state.go
  go/models/c_c_vnic_info.go
  go/models/controller_properties.go
  go/models/event_details.go
  go/models/event_log.go
  go/models/metrics_db_disk_event_details.go
  go/models/server_auto_scale_failed_info.go
  go/models/server_auto_scale_in_complete_info.go
  go/models/server_auto_scale_in_info.go
  go/models/server_auto_scale_out_complete_info.go
  go/models/server_auto_scale_out_info.go
  go/models/service_engine_group.go
  go/models/sub_job.go
  go/models/system_report.go
Labels: AUTO PR, cla-not-required

#2897 AV-198224: Fixed NSX-T migration issues
  python/avi/migrationtools/ansible/ansible_config_converter.py
  python/avi/migrationtools/nsxt_converter/conversion_util.py
  python/avi/migrationtools/nsxt_converter/nsxt_util.py
  python/avi/migrationtools/nsxt_converter/persistant_converter.py
  python/avi/migrationtools/nsxt_converter/policy_converter.py
  python/avi/migrationtools/nsxt_converter/pools_converter.py
  python/avi/migrationtools/nsxt_converter/profile_converter.py
  python/avi/migrationtools/nsxt_converter/vs_converter.py
Labels: cla-not-required

#2909 AV-198224: Fixed NSX-T migration issues - 2
  python/avi/migrationtools/nsxt_converter/pools_converter.py
Labels: cla-not-required, cherrypick-required

#2912 Auto updated assets for go models and clients eng
  go/models/alert_config.go
  go/models/c_c_vnic_info.go
  go/models/saml_identity_provider_settings.go
  go/models/server_auto_scale_failed_info.go
  go/models/server_auto_scale_in_complete_info.go
  go/models/server_auto_scale_in_info.go
  go/models/server_auto_scale_out_complete_info.go
  go/models/server_auto_scale_out_info.go
Labels: AUTO PR, cla-not-required

#2922 Auto updated assets for python 30.2.1
  python/avi/sdk/utils/ansible_utils.py
Labels: AUTO PR, cla-not-required

#2923 Auto updated assets for docs 30.2.1
  docs/ALBServicesConfig/index.html
  docs/ALBServicesFileDownload/index.html
  docs/ALBServicesFileUpload/index.html
  docs/Alert/index.html
  docs/AlertConfig/index.html
  docs/AlertObjectList/index.html
  docs/ApplicationProfile/index.html
  docs/AuthProfile/index.html
  docs/BackupConfiguration/index.html
  docs/CSRFPolicy/index.html
  docs/CloudProperties/index.html
  docs/ControllerProperties/index.html
  docs/DebugController/index.html
  docs/DebugServiceEngine/index.html
  docs/DebugVirtualService/index.html
  docs/FileObject/index.html
  docs/Gslb/index.html
  docs/GslbInventory/index.html
  docs/GslbServiceInventory/index.html
  docs/Image/index.html
  docs/JobEntry/index.html
  docs/NetworkProfile/index.html
  docs/PKIProfile/index.html
  docs/Role/index.html
  docs/SSOPolicy/index.html
  docs/ServiceEngine/index.html
  docs/ServiceEngineGroup/index.html
  docs/ServiceEngineGroupInventory/index.html
  docs/SystemReport/index.html
  docs/UpgradeStatusInfo/index.html
  docs/VirtualService/index.html
  docs/WafPolicy/index.html
  docs/WafProfile/index.html
  docs/index.html
Labels: AUTO PR, cla-not-required

#2920 Auto updated assets for go models and clients 30.2.1
  go/README.md
  go/clients/avi_client.go
  go/clients/pingaccessagent_client.go
  go/models/a_l_b_services_case.go
  go/models/a_l_b_services_config.go
  go/models/alert_object_list.go
  go/models/app_learning_params.go
  go/models/async_patch_state.go
  go/models/auth_profile.go
  go/models/backup_configuration.go
  go/models/c_c_vnic_info.go
  go/models/c_r_l.go
  go/models/c_s_r_f_rule.go
  go/models/capture_tcp.go
  go/models/capture_tcp_filter.go
  go/models/capture_tcp_flags.go
  go/models/cluster_node_add_event.go
  go/models/cluster_node_db_failed_event.go
  go/models/cluster_node_remove_event.go
  go/models/cluster_node_shutdown_event.go
  go/models/cluster_node_started_event.go
  go/models/controller_interface.go
  go/models/controller_properties.go
  go/models/event_details.go
  go/models/event_log.go
  go/models/file_object.go
  go/models/file_object_details.go
  go/models/file_object_details_api_response.go
  go/models/gslb.go
  go/models/gslb_site_runtime_stats.go
  go/models/httpsession_config.go
  go/models/inventory_configuration.go
  go/models/log_mgr_cleanup_event_details.go
  go/models/metrics_db_disk_event_details.go
  go/models/metrics_mgr_debug_filter.go
  go/models/must_checks_info.go
  go/models/p_k_iprofile.go
  go/models/permission.go
  go/models/ping_access_agent.go
  go/models/portal_feature_opt_in.go
  go/models/s_c_t_p_proxy_profile.go
  go/models/s_s_o_policy.go
  go/models/saml_identity_provider_settings.go
  go/models/se_hm_event_gslb_pool_member_details.go
  go/models/se_hm_event_server_details.go
  go/models/security_mgr_debug_filter.go
  go/models/server_auto_scale_failed_info.go
  go/models/server_auto_scale_in_complete_info.go
  go/models/server_auto_scale_in_info.go
  go/models/server_auto_scale_out_complete_info.go
  go/models/server_auto_scale_out_info.go
  go/models/service_engine_group.go
  go/models/sub_job.go
  go/models/system_report.go
  go/models/v_n_i_c.go
  go/models/v_n_i_c_network.go
  go/models/virtual_service.go
  go/models/waf_crs_config.go
  go/session/avisession.go
  go/session/avisession_test.go
Labels: AUTO PR, cla-not-required

#2924 Auto updated assets for java 30.2.1
  java/pom.xml
  java/src/com/vmware/avi/sdk/model/ALBServicesConfig.java
  java/src/com/vmware/avi/sdk/model/AsyncPatchState.java
  java/src/com/vmware/avi/sdk/model/BackupConfiguration.java
  java/src/com/vmware/avi/sdk/model/CRL.java
  java/src/com/vmware/avi/sdk/model/ClusterNodeAddEvent.java
  java/src/com/vmware/avi/sdk/model/ClusterNodeDbFailedEvent.java
  java/src/com/vmware/avi/sdk/model/ClusterNodeRemoveEvent.java
  java/src/com/vmware/avi/sdk/model/ClusterNodeShutdownEvent.java
  java/src/com/vmware/avi/sdk/model/ClusterNodeStartedEvent.java
  java/src/com/vmware/avi/sdk/model/ControllerProperties.java
  java/src/com/vmware/avi/sdk/model/EventDetails.java
  java/src/com/vmware/avi/sdk/model/FileObject.java
  java/src/com/vmware/avi/sdk/model/FileObjectDetails.java
  java/src/com/vmware/avi/sdk/model/Gslb.java
  java/src/com/vmware/avi/sdk/model/GslbSiteRuntimeStats.java
  java/src/com/vmware/avi/sdk/model/HTTPSessionConfig.java
  java/src/com/vmware/avi/sdk/model/InventoryConfiguration.java
  java/src/com/vmware/avi/sdk/model/MetricsMgrDebugFilter.java
  java/src/com/vmware/avi/sdk/model/PKIProfile.java
  java/src/com/vmware/avi/sdk/model/PortalFeatureOptIn.java
  java/src/com/vmware/avi/sdk/model/RestoreParams.java
  java/src/com/vmware/avi/sdk/model/SamlIdentityProviderSettings.java
  java/src/com/vmware/avi/sdk/model/ServiceEngineGroup.java
  java/src/com/vmware/avi/sdk/model/SystemReport.java
Labels: AUTO PR, cla-not-required

#2926 Auto updated assets for go models and clients 30.2.1
  go/clients/avi_client.go
  go/clients/taskjournal_client.go
  go/models/alert_object_list.go
  go/models/controller_properties.go
  go/models/event_log.go
  go/models/journal_action.go
  go/models/journal_error.go
  go/models/journal_info.go
  go/models/journal_object.go
  go/models/journal_summary.go
  go/models/permission.go
  go/models/report_task.go
  go/models/system_report.go
  go/models/task_journal.go
  go/models/task_journal_api_response.go
Labels: AUTO PR, cla-not-required
